### ISSUE TITLE
min-vid window disappears when clicking Test Pilot in toolbar

### ISSUE THREAD

**Issue by davehunt** [meandavejustice/min-vid#353] opened 2016-09-29 09:05 UTC
Steps to reproduce:

1. Start a video playing in min-vid
1. Click the Test Pilot button in the toolbar

Expected:
min-vid window is unaffected

Actual:
min-vid window disappears, but audio continues to play. The only way I've found to restore the window is to start a new video playing.

**Comment by Softvision-VladBacia** [comment] 2016-09-29 11:13
@davehunt, thank you very much for reporting this to us. 

Unfortunately this issue is a dupe of #347 .

**Closed by Softvision-VladBacia** 2016-09-29 11:13 UTC

**Comment by davehunt** [comment] 2016-09-29 14:49
Thanks! Somehow I missed that when looking to see if it had already been reported.
