### ISSUE TITLE
Right-click doesn't work on youtube channel pages

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#21] opened 2016-05-18 22:33 UTC
Oddly, I can't get this to work if I'm on https://www.youtube.com/channel/UClgRkhTL3_hImCAmdLfDE4g and then try right clicking the images or the text titles.

![movies_-_youtube_and_browser_console_and_dist_and_1__pdehaan_pdehaan____dev_tmp_del_min-vid__zsh_](https://cloud.githubusercontent.com/assets/557895/15377001/60e41c78-1d0d-11e6-8790-7a30b363e6f1.png)
**Figure 1:** Right clicking on thumbnail image.

---

![fullscreen_5_18_16__3_32_pm](https://cloud.githubusercontent.com/assets/557895/15377060/d12687f0-1d0d-11e6-939d-48030c799392.png)
**Figure 2:** Right clicking on text link below thumbnail image.

**Comment by meandavejustice** [comment] 2016-05-19 16:21
Nice find.

It's because the actual element delareds this `href` like this

``` html
<a href="/watch?v=qFLpVvFGC1A&list=PLHPTxTxtC0iavTZ4e_3Sw10iMeU2K64Pg"></a>
```
instead of the full url. We are currently checking if the `href` contains a youtube url.

**Comment by wresuolc** [comment] 2016-05-23 18:38
Dupe of #27

**Closed** 2016-05-23 18:38 UTC
