### ISSUE TITLE
[Enhancement] White border around the Min-Vid player in order to be observed easier

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#950] opened 2017-08-03 16:47 UTC
[Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.
- Desktop wallpaper is black or has a darker color

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.soundcloud.com).
2. Send a video video to the Min Vid player.
3. Minimize all other opened windows from desktop.
4. Observe the player.

[Expected result]:
- The Min-Vid player is delimited by a white border so it can be easily noticed.

[Actual result]:
- The Min-Vid player blends with the background
![giphy](https://user-images.githubusercontent.com/9248513/28933028-534668ae-7884-11e7-9321-b58da553685c.gif)

[Notes]:
- Attached a screen recording of the issue:

![find the player](https://user-images.githubusercontent.com/9248513/28933042-5f69de36-7884-11e7-80d6-59bbc00fce4c.gif)

**Comment by 6a68** [comment] 2017-08-03 18:15
The removal of the window border chrome is by design, actually

**Comment by Softvision-VladBacia** [comment] 2017-08-07 12:40
@meandavejustice , @6a68 . I am using a PC setup with dual monitors. When I send a video to the Min-Vid player, the player is opened and has a white border. The white border disappears when I drag the player to the other monitor. In my opinion it will be nice to have a white border all the time especially if the user is using a dark background.

If the white border shouldn't be there, as mentioned in the above comment, then this is an issue.

Here is a GIF with the behavior:

![player border](https://user-images.githubusercontent.com/9248513/29026756-1f5a26c0-7b86-11e7-965d-b976d163ae5b.gif)

**Comment by meandavejustice** [comment] 2017-08-07 13:26
Pulling this out of this milestone, shouldn't have anything to do with sdk changes

**Comment by SoftVision-CiprianMuresan** [comment] 2017-08-17 08:25
Closing as dupe of #894.

**Closed by SoftVision-CiprianMuresan** 2017-08-17 08:25 UTC
