### ISSUE TITLE
Player UI is not updated after clicking Replay

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#238] opened 2016-09-13 12:17 UTC
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.8-dev

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.8-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to the mini player and chose to play it.
4. Fast forward the video to the last few seconds and let it play out.
5. After the video has ended click the "Replay" button.

[Expected result]:
- The UI is updated and the video is replayed.

[Actual result]:
- The video starts playing but the UI is not correctly updated.

[Notes]:
- The Replay/Close screen also takes too long to hide itself and in some cases will be stuck until you click the player controls.
- Reproducible 3/5 times.
- Attached a screen recording of the issue http://goo.gl/hpPIQj.

**Comment by meandavejustice** [comment] 2016-09-13 22:08
possibly related to #211

**Comment by meandavejustice** [comment] 2016-09-16 20:20
Not able to reproduce since #251 was merged

**Closed by meandavejustice** 2016-09-16 20:20 UTC

**Comment by SoftVision-CiprianMuresan** [comment] 2016-09-20 13:50
The issue is no longer reproducible on the latest build (0.1.8).
