### ISSUE TITLE
[Youtube] Min Vid overlay does not appear on the featured video from user or channel pages

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [meandavejustice/min-vid#1032] opened 2017-09-07 14:01 UTC
[Affected versions]:
- Firefox 55 and up
- Min Vid v0.4.3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min Vid add-on version (v0.4.3.) was installed on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a YouTube user or channel page (e.g. https://www.youtube.com/user/smileyomul or https://www.youtube.com/channel/UCfquiJA6_bKLo5m4CLqUphw).
3. Hover over the featured video.
4. Observe the behavior.

[Expected result]:
- The Min Vid overlay appears when hovering over the featured video.

[Actual result]:
- The Min Vid overlay doesn't appear when hovering over the featured video.

[Notes]:
- The issue is only reproducible with the old YouTube UI.
- Added a screen recording with the issue:
![minvid old youtube](https://user-images.githubusercontent.com/31244235/30167093-fcda587e-93ed-11e7-93b9-d1e1764ddaff.gif)

**Comment by meandavejustice** [comment] 2017-09-18 22:56
Unable to reproduce, closing

![2017-09-18--54-18-26-1920x1080_scrot](https://user-images.githubusercontent.com/1844554/30568406-0df49a3a-9ca3-11e7-982a-5fbe6d41316f.png)
![2017-09-18--54-18-24-1920x1080_scrot](https://user-images.githubusercontent.com/1844554/30568409-0e1aff04-9ca3-11e7-92de-1eeb5f8bc6b1.png)
![2017-09-18--54-18-09-1920x1080_scrot](https://user-images.githubusercontent.com/1844554/30568408-0e03e6c0-9ca3-11e7-9917-de8910647c2a.png)
![2017-09-18--54-18-06-1920x1080_scrot](https://user-images.githubusercontent.com/1844554/30568407-0e02c9de-9ca3-11e7-8c9e-09c92cc9c760.png)

**Comment by Softvision-CristinaBadescu** [comment] 2017-09-19 07:21
It seems that you are on the new YouTube UI. This issue is only reproducible with the old YouTube UI.

**Closed** 2017-09-20 15:54 UTC

**Comment by Softvision-CristinaBadescu** [comment] 2017-09-21 15:48
This isssue is no longer reproducible on the latest Min Vid v.0.4.4, built on 21/09/2017.
