### ISSUE TITLE
video stops working after minimize

### ISSUE THREAD

**Issue by wresuolc** [meandavejustice/min-vid#219] opened 2016-09-09 20:23 UTC
This is with min-vid 0.1.8

STR:

0) Linux + Nightly, load https://www.youtube.com/watch?v=m3lF2qEA2cw
1) Click min-vid button
2) pause main player
3) click play in min vid
4) click 'minimize' in min vid

The player minimizes, but it also stops playing.  Restoring the player adds a spinner to the middle of the video but it never restarts playing (even clicking play and such).  Have to close it out and restart to watch again.

**Comment by meandavejustice** [comment] 2016-09-09 20:25
dupe of #133

**Closed** 2016-09-09 20:25 UTC
Labels: duplicate
