### ISSUE TITLE
YouTube channel links can be sent to the mini player

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#279] opened 2016-09-21 13:42 UTC
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.8-dev

[Affected Platforms]:
- All Windows
- All Mac 
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.8-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to YouTube.
3. Right click on the channel name of a YouTube video.

[Expected result]:
- There is no "Send to mini player" option in the context menu.

[Actual result]:
- "Send to mini player" option is available in the context menu

[Notes]:
- Attached a screen recording of the issue https://goo.gl/WTRhWN.

**Comment by meandavejustice** [comment] 2016-09-21 16:30
dupe of #270

**Comment by SoftVision-CiprianMuresan** [comment] 2016-09-22 10:29
This has nothing to do with the issue in #270, where the overlay is missing for videos from channel pages.
This is about the fact that you can send links like [this](https://www.youtube.com/channel/UC-9-kyTW8ZkZNDHQJ6FgpwQ) to the mini player. These links are channel links or user links and are not links to videos.

**Closed** 2016-09-27 20:53 UTC
Labels: in progress

**Comment by SoftVision-CiprianMuresan** [comment] 2016-09-28 13:37
The issue is no longer reproducible on the latest build (0.2.8).
