### ISSUE TITLE
[YouTube] Mid Vid player problem with previous button

### ISSUE THREAD

**Issue by QAtestbegining** [meandavejustice/min-vid#1190] opened 2018-01-21 10:51 UTC
[Affected versions]:

- Firefox Quantum 57.0.4

[Prerequisites]:

- Latest Min-Vid add-on(0.4.7)

[Affected Platforms]:

-  All Windows

[Steps to reproduce]:

1. Open the browser with the profile from prerequisites and navigate to https://youtube.com.
2. Send a video to the Min Vid player by using the "Play now" option.
3. Open the Queue on Min Vid player
4. Start click previous
5. Observe what happens next.

[Expected result]:

- Starts the song from the beginning 

[Actual result]:

- Begins to fill the queue with songs/videos

[Notes]:

- I did not try to reproduce the issue on Mac and Linux

- Attached a screen recording of the issue:
![2018-01-21_12-00-47](https://user-images.githubusercontent.com/35638229/35193332-9aee4284-fea9-11e7-93e1-f0a7542f9d4f.gif)

**Comment by Softvision-CristinaBadescu** [comment] 2018-01-22 08:20
Thanks for reporting this. However, this is a dupe of #727.

**Closed by Softvision-CristinaBadescu** 2018-01-22 08:20 UTC
