### ISSUE TITLE
Min-Vid Was Not Working for Specific Videos on Youtube

### ISSUE THREAD

**Issue by mosmond77** [meandavejustice/min-vid#432] opened 2016-10-17 14:22 UTC
Firefox version = 50.0b6, Windows 10 Pro, 16GB RAM.

While testing the new Min-Vid feature on Firefox I noticed that the feature worked for some videos and not for others.

Steps:
(1) Go to https://www.youtube.com/watch?v=8SzFaEqbLRM (Our Lady Peace - "Somewhere Out There").
(2) Click the Min-Vid icon
(3) Min-Vid dialog appears with the message "Something's gone wrong with this video, Try again Later". See attached screen shot.

I re-tried a few times - 100% reproducible on my end with this video. 

I also tried with other videos and the Min-Vid feature did work with some other videos. The issue seems specific to certain videos.

As a user I would expect this to work for all videos. If it inconsistently works I would be likely to not use the feature.

![min-vid defect screen shot olp](https://cloud.githubusercontent.com/assets/22452020/19441340/6426a622-9453-11e6-9766-a33de7f3e267.JPG)

**Comment by Softvision-VladBacia** [comment] 2016-10-17 14:25
@mosmond77 thank you for reporting this issue to us.

Unfortunately this issue is a dupe of #331.

**Closed by Softvision-VladBacia** 2016-10-17 14:25 UTC
