### ISSUE TITLE
Min Vid player is no longer always on top if the focus is changed while a video/song is loading or playing

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1149] opened 2017-12-19 13:35 UTC
[Notes]:
- Seems that this is a regression caused by issue [#1228841](https://bugzilla.mozilla.org/show_bug.cgi?id=1228841) (see also [#1145)](https://github.com/meandavejustice/min-vid/issues/1145)

Last good revision: b4d98531124336af6ebd253f9e9fd4aa5a53df30
First bad revision: a90317cd54ba39d47ded48c048bfd695e53c7bcd
Pushlog: https://goo.gl/TL7Czc

[Affected versions]:
- Firefox Nightly 59.0a1 (2017-12-19)
- Min-Vid 0.4.6-dev (built on 12/19/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on 0.4.6-dev (built on 12/19/2017) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to the mini player and choose to play it.
3. Click on the Firefox window.
4. Observe the player.

[Expected result]:
- The player remains on top of the Firefox window.

[Actual result]:
- The player is hidden behind the Firefox window.

[Additional notes]:
- Attached a screen recording of the issue: 

![on background](https://user-images.githubusercontent.com/26000308/34159441-f97b0036-e4d1-11e7-98ce-a58c31ed929d.gif)

**Comment by imyxh** [comment] 2018-01-09 01:33
Temporary workaround on Ubuntu (and probably some other Linux distributions):
Use dconf-editor or gsettings to edit org.gnome.desktop.wm.keybindings.always-on-top and set it to a key of your choice, like ['<Alt>F5'].
Open Min Vid, and press that key (e.g. <kbd>Alt</kbd>+<kbd>F5</kbd>) while the window is in focus.
I know this is an OS-based solution that doesn't involve Firefox at all, but it might be helpful for other users as a quick fix, or lead to a way to implement always-on-top behavior easily on Linux.

**Comment by 6a68** [comment] 2018-01-24 22:39
I suspect this was fixed by the fix for #1145. @SoftVision-CarmenFat could you try to duplicate?

**Comment by SoftVision-CarmenFat** [comment] 2018-01-25 12:56
Tested this using latest Nightly 60.0a1 (2018-01-24) and latest Developer Edition 59.0b3 with the latest Min Vid version 0.4.7 - shield study (custom built on 01/25/2018) and here are the results:
- on Windows 10 x64 and macOS 10.12, the issue is fixed: the mini player is always on top;
- on Ubuntu 14.04 x64 and 16.04 x64, the issue is not fixed: the mini player is still hidden behind other apps that are focused.

**Comment by 6a68** [comment] 2018-01-25 16:45
@SoftVision-CarmenFat Thanks for verifying the fix. Would you mind opening a new bug for the linux issue? It seems to be a different root cause, and we're only including windows in the shield study. I'm going to go ahead and close this.

**Closed by 6a68** 2018-01-25 16:45 UTC

**Comment by SoftVision-CarmenFat** [comment] 2018-01-26 09:43
Sure, filed issue #[1211](https://github.com/meandavejustice/min-vid/issues/1211).
