### ISSUE TITLE
Randomly, Min-Vid player continues to move although the mouse button has been released

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [meandavejustice/min-vid#140] opened 2016-08-19 14:00 UTC
[Affected versions]:
- Nightly 51.0a1
- Min-Vid v0.1.1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on (v0.1.1) is installed and enabled on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a video from youtube.com.
2. Click on the overlay icon or right-click on a video from the side-bar and choose from the context menu "Send to mini player".
3. Click and drag the Min-Vid player to a different place.
4. Release the mouse button and keep moving the mouse.

[Expected result]:
- When mouse button is up, the Min-Vid player stops moving.

[Actual result]:
- Min-Vid player continues to move although the mouse button has been released.

[Notes]:
- You might need to repeat steps 3 and 4 a few times in order to reproduce the issue.
- Added a screen recording with the issue: https://goo.gl/us9mrv

**Comment by 6a68** [comment] 2016-08-22 16:31
reopening, I can see this issue with the #142 patch applied.

I see two bugs causing this symptom: 1, the coordinates of the transparent panel aren't correctly pinned to the browser window, you can see this in the screencast GIF where he drags off to the left side of the window and the player disappears (filed as #144). 2, the drag needs to be constrained to not travel outside the container (is overflow:hidden set on html or body or container or something?) (filed as #145).

I think the actual reason the observed bug (drag isn't dropped) occurs is that, if the pointer travels outside the panel's iframe, then the mouseup/drop event will not fire on the iframed window. So, the problem is that #144 makes it natural to try to drag the player outside the iframe's boundaries, then #145 causes the drop event to be lost.

Reopening this bug (in case my guess at the underlying issues is wrong), QA can close it when they can no longer reproduce the issue.

**Closed** 2016-09-06 18:07 UTC
Labels: bug, drag, in progress, size:medium

**Comment by SoftVision-EmilPasca** [comment] 2016-09-22 11:24
The issue is no longer reproducible on the latest build (0.1.9).
