### ISSUE TITLE
Can't Drag videos on OSX Sierra

### ISSUE THREAD

**Issue by MattGrimes** [meandavejustice/min-vid#344] opened 2016-09-28 19:30 UTC
May or may not be related to is issue #339, but on OSX Sierra I can't drag videos at all. Minvid opens a video in the lower left corner of the screen. No matter what I try to move it to a different location, it stays put.

I am also running ALL of the other experiments, so it could be a conflict.

**Comment by bocadillodeatun** [comment] 2016-09-28 19:44
In case additional information is useful, I'm also on Sierra and I've just enabled all experiments to try to reproduce it. Unfortunately (or fortunately, depending on how you see it!) dragging the minvid window works for me.

**Comment by 6a68** [comment] 2016-09-29 00:10
@MattGrimes Thanks for the bug report! #340 tracks very short-term work (this week and next) to move from a panel to a window, which should be better behaved.

**Comment by 6a68** [comment] 2016-09-29 00:27
@MattGrimes which release channel are you using?

**Comment by escapewindow** [comment] 2016-09-29 01:27
Dragging is also broken for me on MacOSX El Capitan 10.11.6, with Nightly 2016-09-28.

**Comment by anshulguleria** [comment] 2016-09-30 06:21
I am using linux 16.04 and firefox developer edition. Dragging is not working in my browser also.

**Comment by MattGrimes** [comment] 2016-10-20 17:32
Seems to be working for me on Firefox 49 now as long as I'm not in fullscreen. Sounds like you are aware of and working on that already in #254.

**Comment by SoftVision-CiprianMuresan** [comment] 2016-10-21 09:40
Based on the last comment, closing this in favor of #254.

**Closed by SoftVision-CiprianMuresan** 2016-10-21 09:40 UTC
