### ISSUE TITLE
"Previous" button doesn't cause previous movie to play

### ISSUE THREAD

**Issue by anitajeziorska** [meandavejustice/min-vid#1083] opened 2017-10-10 16:41 UTC
[Affected versions]
Firefox 56.0.1
Min Vid 0.4.5

[Affected platform]
Windows 10

[Steps to reproduce]
1. Open browser and YouTube website.
2. Open Mid Vid and add few movies to "Queue".
3. Play 2 or 3 movies to have it in "History".
4. Click "Previous" button 

[Expected results]
Previously watched movie opens and play.

[Actual result]
Currently played video doesn' change.
Previous video which we want to open is saved in the end of "Queue"

**Comment by SoftVision-CiprianMuresan** [comment] 2017-10-11 08:03
Hi @anitajeziorska, thanks for the report. However it is a dupe of #727.

**Closed by SoftVision-CiprianMuresan** 2017-10-11 08:03 UTC
