### ISSUE TITLE
Taskbar still on top when playing min-vid

### ISSUE THREAD

**Issue by zer09** [meandavejustice/min-vid#606] opened 2017-02-09 13:41 UTC
When playing min-vid and you have other application that on fullscreen mode the taskbar will stick on top window.
Please check the image uploaded, even the editor on the back is on focus and on-full screen the taskbar is still there. but closing the min vid fix the problem, I also tried other applications and the same happen.

Thanks
![untitled](https://cloud.githubusercontent.com/assets/780780/22785704/6103de70-ef10-11e6-9e7c-117a79879ff6.png)

**Comment by SoftVision-CiprianMuresan** [comment] 2017-02-21 12:59
@zer09, this seems to be the way Windows handles these cases. If you bring any application into foreground while an app is in full screen this will always happen.

I have found two workarounds for the issue:
If you have 2 monitors, you can focus Min-Vid first and then the full screen app second. This will hide the taskbar.
If you have a single monitor, you can set the taskbar to autohide.

Considering this, I'm gonna close this issue. If you think otherwise, please let us know.

**Closed by SoftVision-CiprianMuresan** 2017-02-21 12:59 UTC

**Comment by zer09** [comment] 2017-02-21 13:12
@SoftVision-CiprianMuresan IMHO the first option defeat the purpose of the min-vid, if I have a second monitor I will just play the video on a normal browser tab.

I'm good with the second option, that is what I am doing right now.

I hope there is another way around on this on the future.

Thanks.

**Comment by SoftVision-CiprianMuresan** [comment] 2017-02-21 13:24
@meandavejustice, @6a68, do you think that there is any other way to workaround this behavior on Windows?

**Comment by zer09** [comment] 2017-02-21 14:28
Actually it is working fine on the older builds, I can do fullscreen with the taskbar and the min-vid, but there also other bugs.

**Comment by SoftVision-CiprianMuresan** [comment] 2017-02-21 14:58
This specific behavior is not reproducible on builds before #475, when Min-Vid was part of the browser window. 
After #475 Min-Vid is opened in it's own window and we gain much more this way.
