### ISSUE TITLE
[SoundCloud] [YouTube] Audio from previous SoundCloud song in playlist plays over the top of YouTube video after pausing and playing

### ISSUE THREAD

**Issue by Synj24** [meandavejustice/min-vid#899] opened 2017-06-22 14:11 UTC
[Affected versions]:

- FF Developer Edition 55.0b3
- Min-Vid 0.3.8 (Last Updated 08/06/17

[Affected Platforms]:

- Windows 7

[Steps to reproduce]:

- Send a SoundCloud song to Min-Vid using overlay dialog.
![image](https://user-images.githubusercontent.com/13753370/27437537-77f6e2fa-575a-11e7-87ef-4ae37cbfb4e1.png)

- Add a YouTube video to the queue using plus sign overlay dialog.
![image](https://user-images.githubusercontent.com/13753370/27437579-9d442b94-575a-11e7-8f31-9fca38a573d4.png)

- Skip to next track in Min-Vid.
![image](https://user-images.githubusercontent.com/13753370/27437660-debb8860-575a-11e7-8897-8029c08d7461.png)

- Pause the YouTube video.
![image](https://user-images.githubusercontent.com/13753370/27437711-079bc218-575b-11e7-9ae8-23f72a8b29cb.png)

- Play the video.

[Expected result]:
- Video plays again with original audio.

[Actual result]:
- When you play the YouTube video again the SoundCloud audio is playing alongside the video. If the video is longer than the song then the screen below occurs when the audio has finished; the video audio continues playback.
![image](https://user-images.githubusercontent.com/13753370/27437875-83ce71d2-575b-11e7-942a-59d919d4b43d.png)

[Notes]:
- Haven't tested with vimeo videos yet.
- Bug or feature ? You can find a video with no audio and put some audio to it! :tada: :dark_sunglasses:

**Comment by SoftVision-CiprianMuresan** [comment] 2017-06-22 15:11
@Synj24, thanks for the report.
I was able to reproduce this issue on Windows 10 as well.
The steps are different from #882, but the results seem related.

**Comment by Synj24** [comment] 2017-06-22 15:32
I can confirm this happens when adding videos from Vimeo also.

**Comment by meandavejustice** [comment] 2017-08-03 19:38
fixed in #875

**Closed by meandavejustice** 2017-08-03 19:38 UTC

**Comment by SoftVision-CiprianMuresan** [comment] 2017-08-14 13:09
The issue is no longer reproducible on the latest version of Min Vid (built on 2017/14/08).
