### ISSUE TITLE
Mini player stays black 

### ISSUE THREAD

**Issue by lhirlimann** [meandavejustice/min-vid#355] opened 2016-09-29 11:59 UTC
- Load https://vimeo.com/183609858
- click the mini player icon and start the movie
- switch tab 
  -- mini player is visible
  -- controls are visible and active (eg somehting happens when I click on it)
  -- video is not visible, it plays fine in the original vimeo tab

Env : Fedora/24 , latest nightly, dom.ipc.processCount set to 100.

**Comment by meandavejustice** [comment] 2016-11-16 19:43
Can't reproduce, after #475, closing

**Closed by meandavejustice** 2016-11-16 19:43 UTC
