### ISSUE TITLE
Items from History are not played when clicking on "Previous" button

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#940] opened 2017-08-02 15:46 UTC
[Affected versions]:
- Firefox 53.0.3 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on was previously installed on a clean profile.
- There were multiple items played in Min-Vid. History has multiple items.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a supported platform.
2. While a video is playing click on "Previous" button.

[Expected result]:
- The first item in history starts playing. The item that was previously playing is moved down one position in the Play Queue.

[Actual result]:
- The currently playing video is playing and the first item in history is moved at the end of Play Queue.

[Notes]:
- Attached a screen recording of the issue:
![previous item](https://user-images.githubusercontent.com/9248513/28882063-c5c3c37c-77b2-11e7-836c-701766d02f95.gif)

**Comment by meandavejustice** [comment] 2017-08-04 21:31
dupe of #727

**Closed by meandavejustice** 2017-08-04 21:31 UTC
