### ISSUE TITLE
Firefox will freeze if using shotcut f6 while playing video on min-vid

### ISSUE THREAD

**Issue by zer09** [meandavejustice/min-vid#421] opened 2016-10-12 06:17 UTC
On the first I though it was just random ff freeze.
Step to reproduce:
1. have at least 4 tabs open while a video is playing on min-vid.
2. quickly close the other tabs using ctrl+w.
3. Then quickly press f6 to focus to address bar.

Then ff will freeze the video will stop, but the audio is still there.
Also try to wait ff to respond again after a few min but no success. end up ending the process using taskmanager.

win 7 x64
ff 49.0.1 x64

**Comment by SoftVision-CiprianMuresan** [comment] 2016-10-12 11:26
@zer09, thanks for reporting this to us. 
The steps are actually much simpler than described, you just need to press F6 while a video is playing in Min-Vid. 

The issue is reproducible on all Firefox channels with e10s disabled.
Tested on Windows 10 and Mac OS 10.11. Also it seems to only happen with the F6 shortcut and not Ctrl+L or ALT+D.
Based on the [Support page](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly) for keyboard shortcuts I can see the F6 has conflicting results, it's also used for "Move to Next Frame" as well as focus Location bar.

Based on what I've stated above and the fact that it's only reproducible with e10s disabled, @meandavejustice could something be done on Min-Vid's side or should we log it in Bugzilla?

**Comment by zer09** [comment] 2016-10-12 11:47
@SoftVision-CiprianMuresan  Ohh your right.
Also just tested right now, try to use F6 while the cursor has a focus either a text field, and it wont freeze, but click somewhere blank to lost focus the cursor, then press F6 then it will freeze.

**Comment by 6a68** [comment] 2016-11-17 00:30
I think this is likely fixed by #475, since the old panel used to need to be connected to a parent window, while now the player is its own window.

**Comment by SoftVision-CiprianMuresan** [comment] 2016-11-28 13:15
The issue is no longer reproducible on the latest Min-Vid (0.3.3) build. Verified on Windows 10 and Mac OS 10.11.

**Closed by SoftVision-CiprianMuresan** 2016-11-28 13:15 UTC
