### ISSUE TITLE
Min-Vid player vanishes when accessing TestPilot menu

### ISSUE THREAD

**Issue by MonsieurLanza** [meandavejustice/min-vid#347] opened 2016-09-28 21:25 UTC
Hello, I'm on ArchLinux' firefox 49.0.1 and just installed TestPilot mainly to test minvids. 
So I started testing it, and lanched this video http://www.blendernation.com/2016/09/28/import-svg-inkscape-blender/ 

Worked well, I was able to switch tabs... and decided to see what others testpilots were like. And poof ! My Minvid player vanished. The sound is still here, but the video itself is nowhere. I searched in all tabs, behind the window... No player.

**Comment by gusowski1** [comment] 2016-09-28 21:50
i had this issue to with Firefox 49.0.1 64bit on Windows 8.1 and with an youtube video

**Comment by pdehaan** [comment] 2016-09-28 22:12
Also reported as #343 (on Nightly + macOS El Capitan).
Seems specific to Test Pilot icon. Couldnt reproduce w/ Pocket, Activity Stream, or Page Shot door hangers.

**Comment by 6a68** [comment] 2016-09-29 00:08
@MonsieurLanza Hi, thanks for the bug report. What window manager are you using?

**Comment by synotna** [comment] 2016-09-29 08:04
Ditto in 49.0.1 32bit Windows with a youtube video

**Comment by schalkneethling** [comment] 2016-09-29 09:04
Also 49.0.1 on MacOS Sierra

**Comment by synotna** [comment] 2016-09-29 09:46
@6a68 did you overlook the non-Linux reports before renaming the issue, or should we open separate issues for other platforms? :)

**Comment by Softvision-VladBacia** [comment] 2016-09-29 11:16
This issue is also reproducible on Windows 8.1, Windows 10 with Mozilla Firefox latest release 49.0.2 and latest Firefox Nightly 52.0a1 (Build ID: 20160928030201) using Min-Vid add-on v 0.3.0.

**Comment by MarkWisselink** [comment] 2016-09-29 14:07
I had this same issue on windows 7 with latest firefox dev edition
this not only happens when clicking test pilot in the toolbar, but also some other apps ("Desktop notifications for Android" is where I first noticed it)

**Comment by freaktechnik** [comment] 2016-09-30 10:01
I had this happen when opening the pushbullet panel from within the hamburger menu.

**Comment by mattyc3** [comment] 2016-10-01 00:06
fwiw also reproducible on
ffox 52.0a1 (2016-09-23) (64-bit)
Ubuntu 16.04.1
Gnome 3.20
video disappears but audio continues when trying to drag player - everytime.

**Comment by meandavejustice** [comment] 2016-10-03 15:27
This will be fixed in #340

**Comment by Doc94** [comment] 2016-10-17 15:28
Also in:
W10 - Firefox 49.0.1
The Min-Vid is invisible or "minimize"

**Comment by meandavejustice** [comment] 2016-11-16 19:50
fixed in #475

**Closed by meandavejustice** 2016-11-16 19:50 UTC
