### ISSUE TITLE
Transition of the video in and from the minimize state is made smoothly

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#974] opened 2017-08-11 11:51 UTC
[Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Linux
- All Windows
- All Mac OS

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.youtube.com).
2. Send a video to the Min-Vid player with "Play Now" option.
3. Minimize and Maximize the Min-Vid player window. 

[Expected result]:
- The transition of the video in and from the minimize state is made smoothly. There is no flickering.

[Actual result]:
- When the video scaling is made for the transition of the video in and from the minimize state, the video is flickering and has a latency in scaling.

[Notes]:
- [Here](https://drive.google.com/open?id=0B6QogV2AJFKiSnBMb3lGSW5IcFE) is a screen recording of the issue.

**Comment by SoftVision-CiprianMuresan** [comment] 2017-08-17 08:24
Closing as dupe of #718.

**Closed by SoftVision-CiprianMuresan** 2017-08-17 08:24 UTC
