### ISSUE TITLE
Poor placement of tooltips with longer localizations

### ISSUE THREAD

**Issue by flodolo** [meandavejustice/min-vid#488] opened 2016-11-10 07:33 UTC
Some of them are displayed under controls (good), other overlaps the controls and are quite unreadable.

Mute
![schermata 2016-11-10 alle 08 30 06](https://cloud.githubusercontent.com/assets/3644868/20168107/40c31a64-a720-11e6-928d-ddb60a801a98.png)

Minimize
![schermata 2016-11-10 alle 08 30 22](https://cloud.githubusercontent.com/assets/3644868/20168111/43f02998-a720-11e6-8e5e-54df3e0b4f0e.png)

Maximize (this probably affects en-US too?)
![schermata 2016-11-10 alle 08 35 09](https://cloud.githubusercontent.com/assets/3644868/20168171/ba28ca2a-a720-11e6-8148-9db231cb209c.png)

**Comment by Softvision-VladBacia** [comment] 2016-11-10 10:13
@flodolo , thank you for reporting this.

Unfortunately this issue is a dupe of #461.

**Closed by Softvision-VladBacia** 2016-11-10 10:13 UTC
