### ISSUE TITLE
Work in Tab but not in Min Vid

### ISSUE THREAD

**Issue by harshp2035** [meandavejustice/min-vid#714] opened 2017-04-04 11:00 UTC
This video has been marked as embeddablee by the owner. So plz open in new tab.!!! Link of Video - [](https://www.youtube.com/watch?v=kBlTugtEyqc&t=0 )

**Comment by SoftVision-CiprianMuresan** [comment] 2017-04-04 11:44
Hi @harshp2035, thanks for the report, however it is a dupe of #683. You will find more information there.

**Closed by SoftVision-CiprianMuresan** 2017-04-04 11:44 UTC
