### ISSUE TITLE
Lubuntu 18 + Nightly 60.0a1: Cant move/drag mini-vid window

### ISSUE THREAD

**Issue by wellington1993** [meandavejustice/min-vid#1255] opened 2018-02-12 16:41 UTC
Hi,

**My problem:**

At the latest Firefox Nightly build(60.0a1 and 20180209102946):
I can't move the generated mini-vid window. The video executions and other functionality working fine.

**My linux:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu Bionic Beaver (development branch)"
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
```
**My mini-vid:**

`Min Vid	0.4.8	true	@min-vid`

**My browser:**

 ```
Nome 	Firefox
Versão 	60.0a1
ID da compilação 	20180209102946
Histórico de atualizações 	
Canal de atualização 	nightly
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

```

**Comment by meandavejustice** [comment] 2018-02-12 19:00
dupe of #1212

**Closed by meandavejustice** 2018-02-12 19:00 UTC
