### ISSUE TITLE
Make min-vid player scalable

### ISSUE THREAD

**Issue by Lurtzae** [meandavejustice/min-vid#513] opened 2016-11-25 09:14 UTC
I'm using Firefox with a 1440p and 2160p monitor and the min-vid player is just too tiny with high resolution monitors to be of much help. 
It would be great if you could just scale the min-vid player by dragging its border and set the size manually.

**Comment by 6a68** [comment] 2016-11-29 19:26
Thanks for filing! This is a dupe of #69, and we will eventually add resizing. Note that our upcoming release will make the player resizable, but only on linux (for now).

**Closed by 6a68** 2016-11-29 19:26 UTC
