### ISSUE TITLE
Mini-vid window disappears but continues to play after clicking Test Pilot icon on Firefox toolbar

### ISSUE THREAD

**Issue by btkgamerx** [meandavejustice/min-vid#422] opened 2016-10-12 13:23 UTC
**Steps to reproduce:**

1.  Start a mini-vid streaming video and click play.
2.  Click Test Pilot icon that is located in it's default location in the upper right corner.
3.  Observe the mini-vid window disappear, but you will continue to hear the video play.  

**Other Notes:**
It was observed that you can start another mini-vid stream and the non-visible video will stop playing and a (new?) mini-vid window will appear and can be played.  Step two will always cause the video to disappear whether it is playing or not, but this issue is much more annoying if there is a video playing because there is no way to control it or bring it back other than to start a new mini-vid.

**Expected resolution to issue:**
The mini-vid window remains in the foreground even if the test pilot button is clicked.  The only things that should stop mini-vid from appearing in the foreground is minimizing the firefox window, closing Firefox or using any control on the mini-vid window itself that has the effect of closing the video.  It would be nice in the future if a feature could be added to make the mini-vid window it's own entity so that you could minimize Firefox and you would still see the mini-vid so that you could do more activities then just what you are limited to with Firefox, but for the time being with the way it is currently designed it should operate as previously described.

Thank you,

Gamer X  aka Larry H.

**Comment by Softvision-VladBacia** [comment] 2016-10-12 13:34
@btkgamerx thank you for reporting this.

Unfortunately this issue is a dupe of #347.

**Closed** 2016-10-12 13:34 UTC
