### ISSUE TITLE
Avast detecting as 1/5 rated add-on and attempted to disable it.

### ISSUE THREAD

**Issue by DefiledDahlia** [meandavejustice/min-vid#456] opened 2016-10-20 22:51 UTC
What the Title says, after Firefox updated (presumably a testpilot related one) Avast warned me about NoMore404s and Minvid being horrid user-rated add-ons and attempted to disable them for safety.

(Someone else reported this for NoMore404s already 8 days ago.)

**Comment by SoftVision-CiprianMuresan** [comment] 2016-10-21 06:31
@DefiledDahlia, thank you for reporting this, however it is a dupe of #360.

**Comment by SoftVision-CiprianMuresan** [comment] 2016-10-21 07:50
I might have jumped the horse with this one.

It seems Avast has a lousy way of setting addons reputation is partially based on how often the addon was uninstalled/disabled. See [here](https://forum.avast.com/index.php?topic=156080.0).

**Closed** 2017-04-06 04:29 UTC
