### ISSUE TITLE
The overlay icons should stay and should have hover state

### ISSUE THREAD

**Issue by youwenliang** [meandavejustice/min-vid#737] opened 2017-04-11 09:33 UTC
I expect that the Play Now & Add to Queue icons should stay as long as I'm hovering on the video, but now it will fade away after a few seconds.

Also, when I hover on the "Play Now" icon or "Add to Queue" icon, both icons turn into 100% transparency. I expect that only the one I hover on should change to 100% transparency.

![003](https://cloud.githubusercontent.com/assets/8919308/24902401/8ad82c28-1edc-11e7-88a0-43fc45c368e4.gif)

**Comment by SoftVision-CiprianMuresan** [comment] 2017-04-11 15:07
Hi @youwenliang, thank you for reporting this, however it is a dupe of #439.

**Closed by SoftVision-CiprianMuresan** 2017-04-11 15:07 UTC
