### ISSUE TITLE
Can´t move miniature video of Youtube Min VId

### ISSUE THREAD

**Issue by johan0320** [meandavejustice/min-vid#1108] opened 2017-10-29 23:07 UTC
Hey guys!
I like this idea so much!!
but, i can´t move or adjust measurements of **MinVId**. The image is in the middle of the upper left corner of my screen and it does not allow me to change to the next or previous video.

**Comment by SoftVision-CarmenFat** [comment] 2017-10-30 15:04
Hi @johan0320,
	
Thanks for reporting this.
	
I think you might have encountered issue [#842](https://github.com/meandavejustice/min-vid/issues/842) where sending a Playlist to the mini player moves it on the top of the screen and hides half of it.
Can you please confirm this?

**Comment by johan0320** [comment] 2017-10-30 22:58
Yes, I think so.

**Comment by johan0320** [comment] 2017-10-30 23:02
But today I tried again and I did not have the same problem...:-D

**Comment by johan0320** [comment] 2017-10-30 23:17
apparently it is random, as it has failed again

**Comment by MinionAttack** [comment] 2017-11-02 21:58
I came here to post the same. But I've discovered that if you move the mouse slowly and drag the mind vid to the position you want it works.

The Pop-up get stuck when I try to move it faster. Doing slowly works fine :/

It seems like loses the focus of the mouse. I've checked it clicking and draging it maintaining the mouse clicked and clicking and moving without maintaing the mouse clicked.

Regards!

**Comment by johngruen** [comment] 2018-01-11 20:32
closing as a dupe of #1145

**Closed by johngruen** 2018-01-11 20:32 UTC
