### ISSUE TITLE
Min-Vid player is unresponsive if the last 2 videos from the queue are restricted

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#712] opened 2017-03-31 14:24 UTC
**[Affected versions]:**
-Firefox 52.0 and up
-Min-Vid 0.3.4-dev (built on 3/31/2017)

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.
-Min-VId History and Queue are empty.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video that can be played to the mini player and choose to play it.
3. Add to queue two videos that cannot be played.
5. Wait until the player reaches the last video.
6. Observe the behavior of the player.

**[Expected result]:**
- The user is informed in the video player that the video cannot be played. All buttons are properly working and the user can perform other actions.

**[Actual result]:**
- After the 3 seconds timer has finished for the second video that cannot be played, a error is displayed in the console and the buttons from the player are unresponsive. No other video can be added to the player and queue, player cannot be closed.

**[Additional notes]:**
- Error:
```
min-vid:TypeError: this.props.queue[1] is undefined
Stack trace:
render@resource://min-vid/data/bundle.js:520:1
_renderValidatedComponentWithoutOwnerOrContext@resource://min-vid/data/bundle.js:14046:25
_renderValidatedComponent@resource://min-vid/data/bundle.js:14069:27
_updateRenderedComponent@resource://min-vid/data/bundle.js:13993:31
_performComponentUpdate@resource://min-vid/data/bundle.js:13971:5
updateComponent@resource://min-vid/data/bundle.js:13892:7
receiveComponent@resource://min-vid/data/bundle.js:13794:5
receiveComponent@resource://min-vid/data/bundle.js:19879:5
updateChildren@resource://min-vid/data/bundle.js:13125:9
_reconcilerUpdateChildren@resource://min-vid/data/bundle.js:19163:7
_updateChildren@resource://min-vid/data/bundle.js:19262:26
updateChildren@resource://min-vid/data/bundle.js:19249:7
_updateDOMChildren@resource://min-vid/data/bundle.js:15196:7
updateComponent@resource://min-vid/data/bundle.js:15014:5
receiveComponent@resource://min-vid/data/bundle.js:14976:5
receiveComponent@resource://min-vid/data/bundle.js:19879:5
_updateRenderedComponent@resource://min-vid/data/bundle.js:14001:7
_performComponentUpdate@resource://min-vid/data/bundle.js:13971:5
updateComponent@resource://min-vid/data/bundle.js:13892:7
receiveComponent@resource://min-vid/data/bundle.js:13794:5
receiveComponent@resource://min-vid/data/bundle.js:19879:5
updateChildren@resource://min-vid/data/bundle.js:13125:9
_reconcilerUpdateChildren@resource://min-vid/data/bundle.js:19163:7
_updateChildren@resource://min-vid/data/bundle.js:19262:26
updateChildren@resource://min-vid/data/bundle.js:19249:7
_updateDOMChildren@resource://min-vid/data/bundle.js:15196:7
updateComponent@resource://min-vid/data/bundle.js:15014:5
receiveComponent@resource://min-vid/data/bundle.js:14976:5
receiveComponent@resource://min-vid/data/bundle.js:19879:5
updateChildren@resource://min-vid/data/bundle.js:13125:9
_reconcilerUpdateChildren@resource://min-vid/data/bundle.js:19163:7
_updateChildren@resource://min-vid/data/bundle.js:19262:26
updateChildren@resource://min-vid/data/bundle.js:19249:7
_updateDOMChildren@resource://min-vid/data/bundle.js:15196:7
updateComponent@resource://min-vid/data/bundle.js:15014:5
receiveComponent@resource://min-vid/data/bundle.js:14976:5
receiveComponent@resource://min-vid/data/bundle.js:19879:5
_updateRenderedComponent@resource://min-vid/data/bundle.js:14001:7
_performComponentUpdate@resource://min-vid/data/bundle.js:13971:5
updateComponent@resource://min-vid/data/bundle.js:13892:7
receiveComponent@resource://min-vid/data/bundle.js:13794:5
receiveComponent@resource://min-vid/data/bundle.js:19879:5
_updateRenderedComponent@resource://min-vid/data/bundle.js:14001:7
_performComponentUpdate@resource://min-vid/data/bundle.js:13971:5
updateComponent@resource://min-vid/data/bundle.js:13892:7
receiveComponent@resource://min-vid/data/bundle.js:13794:5
receiveComponent@resource://min-vid/data/bundle.js:19879:5
performUpdateIfNecessary@resource://min-vid/data/bundle.js:13806:7
performUpdateIfNecessary@resource://min-vid/data/bundle.js:19911:5
runBatchedUpdates@resource://min-vid/data/bundle.js:20616:5
perform@resource://min-vid/data/bundle.js:22435:13
perform@resource://min-vid/data/bundle.js:22435:13
perform@resource://min-vid/data/bundle.js:20555:12
flushBatchedUpdates@resource://min-vid/data/bundle.js:20638:7
closeAll@resource://min-vid/data/bundle.js:22501:11
perform@resource://min-vid/data/bundle.js:22448:11
batchedUpdates@resource://min-vid/data/bundle.js:17564:14
enqueueUpdate@resource://min-vid/data/bundle.js:20666:5
enqueueUpdate@resource://min-vid/data/bundle.js:20264:3
enqueueElementInternal@resource://min-vid/data/bundle.js:20456:5
_updateRootComponent/<@resource://min-vid/data/bundle.js:18700:7
scrollMonitor@resource://min-vid/data/bundle.js:18688:5
_updateRootComponent@resource://min-vid/data/bundle.js:18699:5
_renderSubtreeIntoContainer@resource://min-vid/data/bundle.js:18786:9
render@resource://min-vid/data/bundle.js:18834:12
renderApp@resource://min-vid/data/bundle.js:69:3
set@resource://min-vid/data/bundle.js:63:5
 1 timers.js:43
```

```
TypeError: this.props.queue[1] is undefined[Learn More] bundle.js:520:1
	render resource://min-vid/data/bundle.js:520:1
	_renderValidatedComponentWithoutOwnerOrContext resource://min-vid/data/bundle.js:14046:25
	_renderValidatedComponent resource://min-vid/data/bundle.js:14069:27
	_updateRenderedComponent resource://min-vid/data/bundle.js:13993:31
	_performComponentUpdate resource://min-vid/data/bundle.js:13971:5
	updateComponent resource://min-vid/data/bundle.js:13892:7
	receiveComponent resource://min-vid/data/bundle.js:13794:5
	receiveComponent resource://min-vid/data/bundle.js:19879:5
	updateChildren resource://min-vid/data/bundle.js:13125:9
	_reconcilerUpdateChildren resource://min-vid/data/bundle.js:19163:7
	_updateChildren resource://min-vid/data/bundle.js:19262:26
	updateChildren resource://min-vid/data/bundle.js:19249:7
	_updateDOMChildren resource://min-vid/data/bundle.js:15196:7
	updateComponent resource://min-vid/data/bundle.js:15014:5
	receiveComponent resource://min-vid/data/bundle.js:14976:5
	receiveComponent resource://min-vid/data/bundle.js:19879:5
	_updateRenderedComponent resource://min-vid/data/bundle.js:14001:7
	_performComponentUpdate resource://min-vid/data/bundle.js:13971:5
	updateComponent resource://min-vid/data/bundle.js:13892:7
	performUpdateIfNecessary resource://min-vid/data/bundle.js:13808:7
	performUpdateIfNecessary resource://min-vid/data/bundle.js:19911:5
	runBatchedUpdates resource://min-vid/data/bundle.js:20616:5
	perform resource://min-vid/data/bundle.js:22435:13
	perform resource://min-vid/data/bundle.js:22435:13
	perform resource://min-vid/data/bundle.js:20555:12
	flushBatchedUpdates resource://min-vid/data/bundle.js:20638:7
	bound flushBatchedUpdates self-hosted:922:17
	closeAll resource://min-vid/data/bundle.js:22501:11
	perform resource://min-vid/data/bundle.js:22448:11
	batchedUpdates resource://min-vid/data/bundle.js:17564:14
	enqueueUpdate resource://min-vid/data/bundle.js:20666:5
	enqueueUpdate resource://min-vid/data/bundle.js:20264:3
	enqueueSetState resource://min-vid/data/bundle.js:20449:5
	[279]</ReactComponent.prototype.setState resource://min-vid/data/bundle.js:29422:3
	countdown resource://min-vid/data/bundle.js:1125:9
	countdown/< resource://min-vid/data/bundle.js:1128:13
```

- [Here](https://drive.google.com/open?id=0B6QogV2AJFKiNUliVHZvRGpxeDg) is the screen recording of the issue.

**Comment by meandavejustice** [comment] 2017-04-06 19:17
just pushed a fix for this to the queue branch

**Closed by meandavejustice** 2017-04-06 19:17 UTC

**Comment by SoftVision-EmilPasca** [comment] 2017-04-07 11:06
The issue is no longer reproducible on the latest Min Vid with Queue functionality built on 4/7/2017.
