### ISSUE TITLE
Play Now button does not launch MinVid window

### ISSUE THREAD

**Issue by mirzmaster** [meandavejustice/min-vid#1325] opened 2018-05-11 14:21 UTC
On Firefox 61.0b3 the MinVid window no longer launches.  Clicking the button just causes the video to pause, but the MinVid window doesn't show up.

## Min Vid Version
0.4.9 (March 22, 2018)

## Firefox Info
Name: Firefox
Version: 61.0b3
Build ID: 20180507191226
Update Channel: aurora
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:61.0) Gecko/20100101 Firefox/61.0
OS: Darwin 16.7.0
Multiprocess Windows: 4/4 (Enabled by default)
Web Content Processes: 5/4
Enterprise Policies: Inactive
Google Key: Found
Mozilla Location Service Key: Found
Safe Mode: false

**Comment by SoftVision-CiprianMuresan** [comment] 2018-05-11 14:29
Hi @mirzmaster, thanks for the report. However, this is a dupe of #1296.

**Closed by SoftVision-CiprianMuresan** 2018-05-11 14:29 UTC
