### ISSUE TITLE
[YouTube] Video starts from the beginning

### ISSUE THREAD

**Issue by QAtestbegining** [meandavejustice/min-vid#1189] opened 2018-01-20 22:16 UTC
[Affected versions]:

- Firefox Quantum 57.0.4

[Affected Platforms]:

- All Windows

[Prerequisites]:

- Latest Min-Vid add-on(0.4.7)

[Steps to reproduce]:

1. Open the browser with the profile from prerequisites and navigate to https://youtube.com.
2. Play some video
3.When watch it and wanna send to the Min Vid player
4.Observe what happens next.

[Expected result]:

- Continuing play the video from where had to be

[Actual result]:

- The video starts to play from beginning

[Notes]:

- I did not try to reproduce the issue on Mac and Linux
- Attached a screen recording of the issue:
![2018-01-20_23-17-27](https://user-images.githubusercontent.com/35638229/35188546-b23bbd3c-fe3f-11e7-881d-1d816ebcd040.gif)

**Comment by Softvision-CristinaBadescu** [comment] 2018-01-22 08:20
Thanks for reporting this issue. However, this is a dupe of #748.

**Closed by Softvision-CristinaBadescu** 2018-01-22 08:20 UTC
