### ISSUE TITLE
Returning back to Tab issue

### ISSUE THREAD

**Issue by omkarnathsingh** [meandavejustice/min-vid#1068] opened 2017-09-26 02:47 UTC
Can the video being played in pop-up be linked with that playing in tab?
It will be easy then to return back from where it is being played.
I checked for YouTube videos, It starts from beginning after I press "Return to Tab".

**Comment by SoftVision-CiprianMuresan** [comment] 2017-09-26 07:47
Hi @omkarnathsingh, thanks for the report. However it is a dupe of #628.

**Closed by SoftVision-CiprianMuresan** 2017-09-26 07:47 UTC
