### ISSUE TITLE
YouTube video only pauses and min-vid does not appear

### ISSUE THREAD

**Issue by rugk** [meandavejustice/min-vid#463] opened 2016-10-24 17:15 UTC
Test video: https://www.youtube.com/watch?v=C0DPdy98e4c

What happens: Pauses on click, but does not show min vid window.

![youtubeminvidissue](https://cloud.githubusercontent.com/assets/11966684/19655891/dbbc7ae8-9a1d-11e6-91a1-de78ec91796a.gif)

Note that I could only reproduce this once in one browser session (with all YouTube videos, other platforms not tested). After a restart (I assume Firefox restart would have worked, but I had to do a device restart.) everything worked again.

Linux x64, Firefox 49.0.2 (Mozilla binaries)

**Comment by risoul** [comment] 2016-10-25 08:21
Same here, same config.

**Comment by rugk** [comment] 2016-10-25 16:32
Can you reproduce it?

**Comment by risoul** [comment] 2016-11-01 19:07
Soory, can't reproduce, no more issue for me.

**Comment by meandavejustice** [comment] 2016-11-16 18:28
Is this still a bug?

**Comment by 6a68** [comment] 2016-11-17 00:24
Closing. If this bug is still occurring, feel free to reopen

**Closed by 6a68** 2016-11-17 00:24 UTC
