### ISSUE TITLE
Min Vid player is no longer always on top on Mac OS if the focus is changed while a video/song is loading

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#669] opened 2017-03-17 14:13 UTC
[Affected versions]:
- Firefox 52.0 and up
- Min-Vid 0.3.4-dev (built on 3/17/2017)

[Affected Platforms]:
- All Mac

[Prerequisites]:
- Latest Min-Vid add-on with Queue functionality was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to any supported platform.
2. Send a video/song to the mini player and choose to play it. 
3. As soon as you see the loading message, click on the Firefox window.
4. Observe the player.

[Expected result]:
- The player remains on top of the Firefox window.

[Actual result]:
- The player is hidden behind the Firefox window.

[Notes]:
- The issue also seems to be somewhat intermittent.
- The issue is not reproducible if the focus is changed after the loading is done.
- Attached a screen recording of the issue. ([Link](https://drive.google.com/open?id=0B8ICzPJynbchWml6TnROZnNERFU))

**Comment by Softvision-VladBacia** [comment] 2017-04-06 14:01
I have observed this issue also with Min-Vid Queue version on Mac OS X 10.12 without following the above steps. It is happening on all browser versions.

The screen recording of this issue can be found [here](https://drive.google.com/open?id=0B6QogV2AJFKiMTdrT1hwZHVHRDA)

**Comment by meandavejustice** [comment] 2017-04-06 20:37
dupe of #619

**Closed by meandavejustice** 2017-04-06 20:37 UTC
