### ISSUE TITLE
Min VID gets disappeared

### ISSUE THREAD

**Issue by htamilar** [meandavejustice/min-vid#407] opened 2016-10-10 03:16 UTC
1. Play any video in youtube
2. Click on the MIN VID icon to get the small video option.
3. Once the video is loaded in MIN VID, click on the Test-pilot icon on the top right corner.
4. Min VID's video getting disappeared and only audio is audible
5. In order, to stop the audio which is audible, we need to close the entire firefox and reopen it

**Comment by SoftVision-CiprianMuresan** [comment] 2016-10-10 07:13
@htamilar, thank you very much for reporting this to us.

Unfortunately this issue is a dupe of #347.

**Closed by SoftVision-CiprianMuresan** 2016-10-10 07:13 UTC
