### ISSUE TITLE
MinVid UI Disappears After Clicking on Test Pilot Add-on icon

### ISSUE THREAD

**Issue by bkrcrc** [meandavejustice/min-vid#518] opened 2016-12-01 19:09 UTC
Steps:
1 - Go to youtube for a video
2 - Run the video and click on MinVid icon
3 - MinVid UI appears
4 - After clicking on TestPilot Add-on, MinVid disappears.
5 - Video sound still continue to play but video gone..
I couldn't bring it back, I have to close Nightly to stop sound

Please watch: http://recordit.co/USGK3eUai0

Windows 7 SP1 64bit
Nightly 53.0a1 - updated always

Thanks,

**Comment by pdehaan** [comment] 2016-12-01 19:24
Ref #347 (looks like this was fixed in #475 -- but that version may not be published on Test Pilot yet).

**Comment by bkrcrc** [comment] 2016-12-01 19:29
@pdehaan Why there is no release then?
We have to use a buggy version? Last update was more than one month ago.
Thank you for the links by the way, my issue is the same

**Comment by meandavejustice** [comment] 2016-12-01 19:56
@bkrcrc Were planning on doing a release this afternoon. The changes in #475 were large, we wanted to have some time to do thorough testing and the holiday last week messed with our normal release schedule. Sorry for the delay. You should be updated soon.

closing as dupe of #347

**Closed by meandavejustice** 2016-12-01 19:56 UTC
Labels: duplicate
