### ISSUE TITLE
Min-Vid is opened as minimized if it was closed while it was in the minimized state

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#256] opened 2016-09-14 15:17 UTC
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.8-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.8-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to the mini player and chose to play it.
4. Minimize and then close the player.
6. Send a video to the mini player and observe the player state.

[Expected result]:
- Min-Vid player starts as maximized.

[Actual result]:
- Min-Vid player starts as minimized and player control bar is positioned in the same place as the maximized player state.

[Additional Notes]:
- Attached a screen recording of the issue https://goo.gl/0e31xy.

**Comment by meandavejustice** [comment] 2016-09-14 15:42
We could probably just put a call to `adjustHeight` where we launch the video.

**Comment by meandavejustice** [comment] 2016-09-27 20:59
Not sure that this is a bug. I'm willing to close this as intended behavior

**Closed** 2016-09-27 22:13 UTC

**Comment by SoftVision-CiprianMuresan** [comment] 2016-09-28 11:53
At least the player now opens in the same position is was closed, so I'm ok with this.
