### ISSUE TITLE
Ability to clip a window

### ISSUE THREAD

**Issue by Vladsg** [meandavejustice/min-vid#1220] opened 2018-01-28 13:12 UTC
Ability to fix a window with video on top of all other windows

**Comment by Softvision-CristinaBadescu** [comment] 2018-01-29 16:25
Thanks for reporting this. However, this is a known issue and a dupe of #1211 and #1149. Shortly, a fix will be pushed into the release that will fix this problem on Windows and Mac OS'es.

**Closed by Softvision-CristinaBadescu** 2018-01-29 16:25 UTC
