### ISSUE TITLE
Min Vid overlay no longer works after the add-on is updated, until the page is refreshed

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#993] opened 2017-08-18 12:24 UTC
[Affected versions]:
- Firefox 55 and up
- Min-Vid 0.4.1 (built on 8/18/2017)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (0.4.1) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.youtube.com).
2. Update Min Vid in a new tab.
3. Switch back to the tab from Step 1.
4. Hover a video thumbnail and click the "Play now" option.
5. Observe the behavior.

[Expected result]:
- The player is opened in the top-left corner of the screen.

[Actual result]:
- Nothing happens.

[Notes]:
- The issue is also reproducible on Vimeo and Soundcloud.
- Attached a screen cast of the issue:
![min vid overlay no longer works after updating](https://user-images.githubusercontent.com/18304511/29458259-d8c00d34-8426-11e7-9af1-d0faaa2e9714.gif)

**Comment by meandavejustice** [comment] 2017-08-18 16:04
This makes sense, behavior should be better once #994 is fixed.

**Comment by meandavejustice** [comment] 2017-08-28 15:24
closing as a dupe of #994

**Closed by meandavejustice** 2017-08-28 15:24 UTC
