### ISSUE TITLE
setState(...) warnings are displayed in Browser Console when hovering the Min-Vid player buttons

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#437] opened 2016-10-18 15:31 UTC
**[Affected versions]:**
-Firefox 45.0 and up
-Min-Vid v0.3.1

**[Affected Platforms]:**
-All Windows

**[Prerequisites]:**
-Latest Min-Vid add-on version (0.3.1-dev) was previously installed on a profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Open the Browser Console.
4. Send a video to the mini player.
5. Hover Min-Vid player buttons one by one and observe the 

**[Expected result]:**
-There should be no warnings in the console while hovering the Min-Vid player buttons.

**[Actual result]:**
-The following warning message is displayed multiple times in the Browser Console when hovering Min-Vid player buttons: `Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.` 

**[Additional Notes]:**
-This issue was tested with Latest Nightly (Build ID: 20161018030211) and latest Dev Edition (Build ID: 20161018004015).
-[Here](https://drive.google.com/open?id=0B6QogV2AJFKiNXJjZU04dU9PeW8) is a video of the issue.

**Comment by meandavejustice** [comment] 2016-10-18 15:48
dupe of #113

**Closed by meandavejustice** 2016-10-18 15:48 UTC
