### ISSUE TITLE
Min Vid strats playing the video from wrong play time

### ISSUE THREAD

**Issue by sisil6** [meandavejustice/min-vid#1241] opened 2018-02-07 09:00 UTC
Firefox version: 
58.0.1(x64)

OS parameters:
Edition Windows 10 Pro
Version 1709
Build 16299.192
Processor Intel(R) Core(TM) i7-6700HQ CPU @ 2.6Ghz
Installed RAM 8.00 GB (7.80 GB usable)

Min Vid version:
0.4.8

Steps:
1. Open Firefox brouser 
 Expected result: The home page of the brouser should be displayed.
 Actual result: passed.

2. Load a video page. Example https://www.youtube.com/watch?v=4quvCgiuBxs&t=24
 Expected result: The page shold appear and the video should start.
 Actual result: passed.

3. Waith for the video to be played for one minute and then pause it
 Expected result: The video should play for one minute and then pause.
 Actual result: passed.

4. Click on the Min Vid icon in the upper left corner of the video to load the program
  Expected result: A small panel of Min Vid should appear. The video should appear at paused in the one minute time of the video.
 Actual result: Failed. The video reload from the beggining and start playing.

Screenshot:
![screenshot 4](https://user-images.githubusercontent.com/35563649/35907180-d005cb82-0bf5-11e8-96cd-bdbb4f539fe8.png)

**Comment by SoftVision-CarmenFat** [comment] 2018-02-07 09:54
Thanks for reporting this issue. However, this is a dupe of #748.

**Closed by SoftVision-CarmenFat** 2018-02-07 09:54 UTC
