### ISSUE TITLE
Won't play YouTube videos in playlist

### ISSUE THREAD

**Issue by aewens** [meandavejustice/min-vid#1116] opened 2017-11-07 18:07 UTC
If I choose Play Now or Add to queue from a YouTube video in the Water Later playlist, it will just show the loading animation indefinitely. If I remove the playlist bit from the URL to where just the watch?v=<hash> bit remains, min-vid will then load the video fine. The issue persists after stopping all Firefox processes and relaunching.

Update:
After further testing it seems in any playlist this seems to be the case as well, not just for the Watch Later playlist.

I'm using Firefox version 57.0b14 on macOS Sierra (10.12.6).

**Comment by SoftVision-CarmenFat** [comment] 2017-11-08 12:42
Hi @aewens, 

Thanks for the report, however this seems to be a dupe of #1087.

**Closed by SoftVision-CarmenFat** 2017-11-08 12:42 UTC
