### ISSUE TITLE
Min Vid no longer works with Nightly 57.0a1 (Mac)

### ISSUE THREAD

**Issue by TheMacDude** [meandavejustice/min-vid#976] opened 2017-08-11 17:44 UTC
[Affected Versions]
Firefox Nightly 57.0a1 (2017-08-11) (64-bit)
Min Vid 0.3.9 (origin: Mozilla Test Pilot)

[Affected Platforms]
macOS

[System Specifications]
iMac (21.5-inch, Mid 2014)
1.4 GHz Intel Core i5
8 GB 1600 MHz DDR3
Intel HD Graphics 5000 1536 MB

[Steps to Reproduce]
1. Update to latest version of Firefox Nightly [at time of post 57.0a1 (2017-08-11)] on macOS
2. Visit a supported video streaming site (www.youtube.com was used during testing; others were not tested and may or may not have the problem in question)
3. Open a video; the selector won't appear in the video window

[Expected Result]
The Min Vid menu will appear in the video window, allowing one to switch playback over to using Min Vid or add the video to the Min Vid queue.

[Actual Result]
The Min Vid menu will not appear in the video window as expected, and the site behaves as it would if Min Vid were not installed. Min Vid cannot be launched or used because the appropriate selector will not appear with which to do so. 

[Additional Notes]
Min Vid behaves as expected in the stable release of Mozilla Firefox.
This problem could persist in Nightly 57.0a1 (2017-08-11) for other operating systems as well, but macOS was the only system tested.

![screen shot 2017-08-11 at 2 27 25 pm](https://user-images.githubusercontent.com/30934820/29226789-5ff37286-7ea1-11e7-814d-1c3dfbbf06a0.png)

**Comment by jonathanKingston** [comment] 2017-08-12 13:48
Looks like the same issue as: https://github.com/mozilla/testpilot-containers/issues/725
Which was caused by: https://bugzilla.mozilla.org/show_bug.cgi?id=1350646

**Comment by madeindjs** [comment] 2017-08-16 14:13
Same issue for me on 

* Linux Mint: Linux 4.8.0-58-generic
* Firefox 57.0a1 
* compilation 	20170816100153
* Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by meandavejustice** [comment] 2017-08-16 17:40
Pushing a fix this afternoon, sorry for the inconvenience

**Comment by meandavejustice** [comment] 2017-08-16 22:38
Just pushed a fix for this. Thanks for everyone's patience :)

**Closed by meandavejustice** 2017-08-16 22:38 UTC
