### ISSUE TITLE
MinVid doesn't stay on foreground in OS X

### ISSUE THREAD

**Issue by tanmaybaranwal** [meandavejustice/min-vid#619] opened 2017-02-22 12:00 UTC
Hi! I am on El Capitan. The MinVid went into the background when I selected Pages. Now it's not staying on the foreground.

**Comment by Softvision-VladBacia** [comment] 2017-02-22 12:15
@tanmaybaranwal thank you for reporting this. I have encountered a similar issue yesterday but i couldn't reproduce it the second time. 

Can you give me a little more info?
- Firefox version
- Min-Vid version (from where it was installed)
- Any further steps to reproduce
- Does it happen with a new profile?
- Does it happen if you reinstall the experiment?

**Comment by tanmaybaranwal** [comment] 2017-02-22 12:29
@Softvision-VladBacia I faced one more issue also when kept on loop, the video player shows the replay button (while the song is being played).

Firefox version: 51.0.1
MinVid was installed by TestPilot today.
I just restarted the Firefox, open the video in MinVid and clicked on Android Studio. It's gone.
New Profile?
Yeah.

**Comment by Softvision-VladBacia** [comment] 2017-02-22 12:38
> @Softvision-VladBacia I faced one more issue also when kept on loop, the video player shows the replay button (while the song is being played).
There is an issue logged for that: #409 .

I can confirm the issue that Min-Vid doesn't stay on forground in OS X 10.12.

**Comment by Softvision-VladBacia** [comment] 2017-02-22 14:46
> @Softvision-VladBacia I faced one more issue also when kept on loop, the video player shows the replay button (while the song is being played).

There is an issue logged for that: #409 .

I can confirm the issue that Min-Vid doesn't stay on forground in OS X 10.12.

**Comment by 6a68** [comment] 2017-04-13 17:29
I'm seeing the same thing on MacOS Sierra, updated the bug title

**Comment by fturcheti** [comment] 2017-05-04 23:19
I can confirm this issue too. I'm currently running:

- Min Vid 0.3.6
- Firefox 54.0b4
- OSX 10.11.6

Tested in my default profile and in a new one.

**Comment by 6a68** [comment] 2017-05-09 15:16
The relevant code is here: https://github.com/meandavejustice/min-vid/blob/master/lib/topify.js#L61-L66

**Comment by fnrcum** [comment] 2017-06-09 12:31
It's easy to reproduce, I'm on Sierra and it always reproduces on a video i am starting for the first time. 
After i close mid-vid and re start it, it will stay in the foreground

**Comment by 6a68** [comment] 2017-06-16 18:52
@noitidart Hi! I'm not sure how to debug this on mac. Do you have any suggestions around how I could either cast the window number and log it, or (better) intercept what's happening via XCode?

**Comment by Noitidart** [comment] 2017-07-01 00:02
Hi @6a68 - excuse the delay please.

Yes the window number can be got like this - `[NSWindow windowNumber]` - https://developer.apple.com/documentation/appkit/nswindow/1419068-windownumber?language=objc

So with ostypes this would be:

```
const nswin = ....;
const nswinNum = ostypes.API('objc_msgSend')(nswin, ostypes.HELPER.sel('windowNumber'));
console.log('nswinNum:', nswinNum);
```

I didn't test this, this is just off the top of my head.

I am not sure how to intercept via XCode, I never could as I did my mac stuff on a super slow VM. :(

**Comment by Noitidart** [comment] 2017-07-01 00:04
Also the issue can be that the NSWindow* changes during window.open, I had this issue and resolved it by doing a setTimeout then topifying - I could never explain this. But it has consistently worked for me. It seems it initially has X nwin then changes to Y, although the window never appears to destroy and recreate, its the weirdest thing.

**Comment by 6a68** [comment] 2017-07-07 19:49
@Noitidart thanks for the suggestions! your comment landed just as I was traveling from a work week, so please excuse my delay in thanking you ^_^

**Comment by Noitidart** [comment] 2017-07-09 18:57
No problem sir, thank you! I'm pretty sure the setTimeout and re-topify should fix this. :) Something weird with window.open in Firefox. I can't explain it. :( But I hit the issue in [NativeShot](https://addons.mozilla.org/en-US/firefox/addon/nativeshot/?src=github) as well and this is how I fixed it.

**Comment by sunraerae** [comment] 2017-07-25 17:35
Hey, idk if this is a bug people are trying to solve, but I am running Firefox on a Mac OS X El Capitan 10.11.6 and the video will sometimes drop into the background.  Today this happened when I had 3 windows open.  I would click into a window that I had open before MinVid started and MinVid would "disappear."  

I reset the browser (quit firefox, reopened all windows) then started the MinVid and it stayed in the foreground as expected.

**Comment by Noitidart** [comment] 2017-07-26 18:49
@sunraerae when the window does not remain in front, does this happen immediately after window opens, or after some time of the window being open?

**Comment by 6a68** [comment] 2017-08-04 18:26
This should be fixed when the webextension version is released

**Closed** 2017-08-09 18:33 UTC

**Comment by SoftVision-CiprianMuresan** [comment] 2017-08-14 13:11
The issue is no longer reproducible on the latest version of Min Vid (built on 2017/14/08).

**Comment by 6a68** [comment] 2017-08-14 18:12
\o/
