### ISSUE TITLE
Video disappearing when I open my history.

### ISSUE THREAD

**Issue by Falcoholic** [meandavejustice/min-vid#406] opened 2016-10-09 13:45 UTC
When I have a video playing, and I open my history bar, the video disappears. The audio plays on, but the video just vanishes, and I can't get it back. Hope this little issue report helps.

**Comment by Falcoholic** [comment] 2016-10-09 13:49
Oops, this was reported before. How do you delete posts?

**Comment by SoftVision-CiprianMuresan** [comment] 2016-10-10 07:14
@Falcoholic, thank you very much for reporting this to us.

Unfortunately this issue is a dupe of #380.

**Closed by SoftVision-CiprianMuresan** 2016-10-10 07:14 UTC
