### ISSUE TITLE
Muting and then Unmuting the video do not remember the previous volume range

### ISSUE THREAD

**Issue by shashikumarraja** [meandavejustice/min-vid#388] opened 2016-10-04 13:36 UTC
1.Set a volume range(say 80%)
![6](https://cloud.githubusercontent.com/assets/13863716/19076199/774c8d22-8a65-11e6-82ed-0a85d389c513.png)

2.Now Mute it.
![7](https://cloud.githubusercontent.com/assets/13863716/19076221/83e4be60-8a65-11e6-9a35-3d6778242bbc.png)

3.Again Unmute the video.
![8](https://cloud.githubusercontent.com/assets/13863716/19076229/8947e634-8a65-11e6-8752-8e2ed667934a.png)

4.Ideally the volume should revert back to previous setting(80% in this case)
5.Presently it is reverting to about 50% in all the scenarios.

Testing Environment-
OS-Unbuntu 16.04 LTS
Browser- Firefox version 49.0

**Comment by Softvision-VladBacia** [comment] 2016-10-04 13:40
@shashikumarraja thank you for reporting this.

Unfortunately this issue is a dupe of #335 .

**Closed by Softvision-VladBacia** 2016-10-04 13:40 UTC
