### ISSUE TITLE
min-vid:Warning: setState(...): Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#164] opened 2016-09-01 00:27 UTC
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18150925/859b59de-6f9f-11e6-9114-6abd5b62f0ad.png)

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/18150999/1844d5f8-6fa0-11e6-8edf-71e83410845b.png)

Trying to get some solid repro steps for this, but it seems to just be:

1. Open Browser Console
2. Install latest min vid add-on
3. Go to https://reddit.com/r/videos and play a video in the min vid player
4. Move your cursor over the min vid player, then off, then on, then off, etc.

My Browser Console ends up looking like:

![browser_console](https://cloud.githubusercontent.com/assets/557895/18150950/c93e17da-6f9f-11e6-9a0f-6dc4089366d3.png)

> **min-vid** Warning: `setState(...)`: Can only update a mounted or mounting component. This usually means you called `setState()` on an unmounted component. This is a no-op. Please check the code for the undefined component. (bundle.js:1806)

The **bundle.js:1806** doesn't look very interesting:

![jar_file____var_folders_qc_g_f0szh95k1fzph34rhmf5jw0000gp_t_8b16e12d-c461-4997-9bfe-f1bb1c6e4a99_extensions__min-vid_xpi__data_bundle_js](https://cloud.githubusercontent.com/assets/557895/18150991/0f50f800-6fa0-11e6-9834-d5fd91b13f73.png)

**Comment by meandavejustice** [comment] 2016-09-01 15:51
dupe of #113 It's an upstream bug, I've yet to dig into fix. Planning to address this after mvp milestone is complete

**Closed by meandavejustice** 2016-09-01 15:51 UTC
Labels: duplicate
