### ISSUE TITLE
Min-Vid player buttons are unresponsive, after the player is minimized and maximized several times on Ubuntu

### ISSUE THREAD

**Issue by Softvision-VladBacia** [meandavejustice/min-vid#333] opened 2016-09-28 14:57 UTC
**[Affected versions]:**
- Firefox 45.0 and up
- Min-Vid 0.2.8 signed

**[Affected Platforms]:**
- All Linux

**[Prerequisites]:**
- Min-Vid add-on version (0.2.8) was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to www.youtube.com. 
2. Send a video to the Min-Vid player.
3. Minimize the Min-Vid player.
4. Maximize the Min-Vid player.
5. Repeat steps 4 and 5 twice.

**[Expected result]:**
- Every time the "Minimize" button is clicked the player is minimized and every time the "Maximize" button is clicked the player is maximized.

**[Actual result]:**
- The Min-Vid player buttons are unresponsive. Browser must be restarted or reinstall the Min-Vid add-on. 

**[Notes]:**
-After the Min-Vid player enters this state the only options for the user to recover are: 1. restart the browser; 2. if a browser restart is not an option for the user and the work that he is doing in Firefox, then the add-on needs to be reinstalled.
-[Here](https://drive.google.com/open?id=0B6QogV2AJFKiYk5FV2s5STRmeE0) is a video of the issue.

**Comment by meandavejustice** [comment] 2016-11-16 20:01
having trouble reproducing this

**Comment by 6a68** [comment] 2016-11-17 00:36
I bet this will be fixed by #475

**Comment by SoftVision-EmilPasca** [comment] 2016-11-17 13:15
The issue is no longer reproducible on the latest build (0.3.3), re-tested with latest Nightly 53.0a1 on Ubuntu 14.04 x64.

**Closed** 2016-11-17 15:32 UTC
