### ISSUE TITLE
[Nightly / OSX Sierra] Can't drag min-vid window to second monitor on a Mac

### ISSUE THREAD

**Issue by Verdi** [meandavejustice/min-vid#339] opened 2016-09-28 17:45 UTC
I'm using Nightly and mac OS Sierra. When I try to drag the min-vid window to another monitor (my laptop screen) it flickers and bounces back to the original screen.
Here's a screen recording of the second monitor - https://www.dropbox.com/s/rrwokc0a3xhse5x/cantdragtoanotherscreen.mp4?dl=0

**Comment by aaronraimist** [comment] 2016-09-28 23:01
For me it flickers a little but still works when dragging between screens so I cannot reproduce this issue.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0
Build ID: 20160928030201

**Comment by 6a68** [comment] 2016-09-29 00:25
The current implementation uses a panel, which is designed to stick to a single screen. #340 tracks work to move to a window instead, which should fix this problem.

**Comment by meandavejustice** [comment] 2016-11-16 19:58
This should be fixed in #475

**Closed by meandavejustice** 2016-11-16 19:58 UTC
