### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#113] opened 2016-07-29 00:40 UTC
Looking at https://vimeo.com/176291464 and after sending a video to the Min-Vid player and minimizing the player, I somehow got this message in my Browser Console (Tools > Web Developer > Browser Console)

> Warning: `setState(...)`: Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.
> 
> &mdash; via bundle.js:20922

![jar_file____users_pdehaan_library_application_20support_firefox_profiles_118pl5yo_activity-stream-recommendations_extensions__min-vid_xpi__data_bundle_js](https://cloud.githubusercontent.com/assets/557895/17234095/5bd6d576-54ea-11e6-9be6-428f9ec8b1fa.png)

**Comment by meandavejustice** [comment] 2016-07-29 19:32
Looks like an upstream bug. I commented on it here, https://github.com/wwayne/react-tooltip/issues/148#issuecomment-235926176. Just forgot to link it in my pr

**Comment by rugk** [comment] 2016-10-05 14:45
I can reproduce this too.

```
console.error: min-vid: 
  Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.
console.error: min-vid: 
  Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.
console.error: min-vid: 
  Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.
```

**Comment by meandavejustice** [comment] 2017-01-16 18:52
No longer seeing this, closing

**Closed by meandavejustice** 2017-01-16 18:52 UTC
Labels: code-quality, good-first-bug, size:small
