### ISSUE TITLE
Send Video to Minvid Appearing Multiple Times in Context Menu

### ISSUE THREAD

**Issue by t-kitsune** [meandavejustice/min-vid#613] opened 2017-02-15 04:09 UTC
I have a weird issue where minvid will add around 14 "Send Video to Minvid" context items. I don't know if this is a known issue.

Firefox Build: Nightly (latest)
OS: Windows 10

**Comment by SoftVision-CiprianMuresan** [comment] 2017-02-15 07:38
Hi @t-kitsune, thank you for reporting this. However, I think this is a duplicate of #490. 
Could you leave a comment there with how you managed to get that context menu items, or a link to the page that had the issue?

**Closed by SoftVision-CiprianMuresan** 2017-02-15 07:38 UTC
