### ISSUE TITLE
the video is closed when 'test pilot' button is pressed

### ISSUE THREAD

**Issue by asurkov** [meandavejustice/min-vid#366] opened 2016-09-30 01:54 UTC
the video is closed, audio still working, when 'test pilot' button is pressed, and its popup pops up

**Comment by SoftVision-CiprianMuresan** [comment] 2016-09-30 08:29
@asurkov, thank you very much for reporting this to us.

Unfortunately this issue is a dupe of #347.

**Closed by SoftVision-CiprianMuresan** 2016-09-30 08:29 UTC
