### ISSUE TITLE
Possible video playback issue (diagonal videos)

### ISSUE THREAD

**Issue by johngruen** [meandavejustice/min-vid#459] opened 2016-10-21 15:14 UTC
Reported on Nightly on Mac OS... there may be a relationship between Min Vid and a video playback issue. No STR, but here's a screenshot

![screenshot_2016-10-17__16_21](https://cloud.githubusercontent.com/assets/3323249/19603535/d36cd4dc-97b1-11e6-979f-f7e92a57006f.png)

**Comment by Softvision-VladBacia** [comment] 2016-10-24 07:23
@johngruen , this issue seems to be related with what Peter has reported in #364.

**Comment by meandavejustice** [comment] 2016-11-16 18:29
Should have been fixed in #475

**Comment by Softvision-VladBacia** [comment] 2016-11-21 10:25
We didn't see the issue to reproduce on Mac OS X 10.12 with the latest Min-Vid build v0.3.3-dev using latest Firefox release 50.0 and latest Nightly build (Build ID: 20161120030205). 
We've checked the scenarios described in #364 and they are no longer reproducible,

**Closed** 2016-11-21 16:13 UTC
