### ISSUE TITLE
Windows hides when 'Test Pilot' button is pressed

### ISSUE THREAD

**Issue by Heathland** [meandavejustice/min-vid#374] opened 2016-09-30 09:10 UTC
When you have the min vid player open and you press the 'Test Pilot' button, the windows hides but still continues to play.
The only way to get the window to show again is to open up another video into it.

**Comment by SoftVision-CiprianMuresan** [comment] 2016-09-30 09:30
@Heathland, thank you very much for reporting this to us.

Unfortunately this issue is a dupe of #347.

**Closed by SoftVision-CiprianMuresan** 2016-09-30 09:30 UTC
