### ISSUE TITLE
min-vid window dont move

### ISSUE THREAD

**Issue by Westfallx** [meandavejustice/min-vid#1186] opened 2018-01-19 09:48 UTC
U cant move  mind-vid on firefox developer 59.0

**Comment by Softvision-CristinaBadescu** [comment] 2018-01-19 10:05
Thanks for reporting this issue, however this is a dupe of #1145. The development team was informed and we'll see what course of action will be taken.

In the meantime you can either use your current profile with Beta or Firefox Release to bypass the issue.

**Closed by Softvision-CristinaBadescu** 2018-01-19 10:05 UTC
