### ISSUE TITLE
jeffmap in fullscreen prevents minvid from showing

### ISSUE THREAD

**Issue by asurkov** [meandavejustice/min-vid#368] opened 2016-09-30 01:59 UTC
open http://www.thekillarneymap.com/ in chrome, enter into fullscreen, while minvid is showing, minvid is not visible anymore

**Comment by Softvision-VladBacia** [comment] 2016-09-30 09:07
@asurkov thank you for reporting this. 
We have verified this on Windows 8.1 using latest Nightly 52.0a1 with Min-Vid v0.3.0 and didn't encounter the issue. 
We **can reproduce** this issue on Mac OS X 10.12 using latest Nightly 52.0a1 with Min-Vid v0.3.0.

**Comment by meandavejustice** [comment] 2017-04-06 04:19
closing stale issue

**Comment by Softvision-VladBacia** [comment] 2017-04-06 14:02
reopening due to #669

**Comment by meandavejustice** [comment] 2017-04-06 16:25
@Softvision-VladBacia Can we not just leave #669 open and close this issue? I'm trying to get rid of dupes

**Comment by Softvision-VladBacia** [comment] 2017-04-07 09:01
Closing this as dupe of #619 and #669 . Thank you.

**Closed by Softvision-VladBacia** 2017-04-07 09:01 UTC
