### ISSUE TITLE
Can't drag min-vid window

### ISSUE THREAD

**Issue by hiseni** [meandavejustice/min-vid#1024] opened 2017-09-01 20:38 UTC
Min-vid window appear to be **non draggable** && **non resizable** on latest Nightly on Linux.
It just sit at the center of my monitor.

This behavior makes so lovely extension completely useless. :cry: 

Please, have a look at this problems.

P.S.: Ping me for some help if needed.
:heart:  this project.

**Comment by AmrEldib** [comment] 2017-09-02 23:31
Same behavior on Windows 10. Popup appeared behind task bar which I have at the top
I'm using Nightly as well.

**Comment by SoftVision-PaulOiegas** [comment] 2017-09-04 10:11
@hiseni Hi and thanks for your report. This is a regression caused by Nightly that only reproduces on Linux.

Last good revision: a972e0fb330b7229f86b26dfc75279b44a41c25b
First bad revision: 0ab0630eec0c15b591b379454fe59344bac62290
Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=a972e0fb330b7229f86b26dfc75279b44a41c25b&tochange=0ab0630eec0c15b591b379454fe59344bac62290

Seems like Bug 1394556 introduced this new behavior.

@meandavejustice, is there anything we can do on our side?
Ciprian also opened Bug 1396512 in Bugzilla for the Foreground issue (#1023) that has the same root cause like this one.

@AmrEldib The issue you have mentioned has other root cause on Windows and it's already tracked under #499.

**Comment by 6a68** [comment] 2017-09-05 22:03
Hi all, thanks for the bug report.

The recent change that landed is not a regression; it enforces strict mode for any scripts loaded using the Firefox JSM importer (`Cu.import`). It seems that a third-party library that we use for platform-specific hacks (@noitidart's ostypes library) violates strict mode, so the loader refused to load the file.

I think #1029 might fix this bug, as well as #1023. (I'm surprised we aren't getting reports of breakage on windows, because ostypes has the same problems on that platform...)

**Comment by 6a68** [comment] 2017-09-06 16:07
Just to confirm, #1029 fixes this bug for me on unity / ubuntu, Dave similarly had good luck with xfce. Should have a fix out shortly

**Closed** 2017-09-06 16:08 UTC
