### ISSUE TITLE
Mini Player Won't Open

### ISSUE THREAD

**Issue by kaydeath** [meandavejustice/min-vid#351] opened 2016-09-29 02:37 UTC
Whenever I click on the button, the video will freeze, but nothing else will happen. I have waited for five minutes, and still nothing has happened. I did not see anyone with a similar problem, though I could have missed it.

**Comment by meandavejustice** [comment] 2016-09-29 03:30
Hey @kaydeath thanks for the report, can you give me a little more info?

* Operating system
* firefox version
* link to video link (if u feel comfortable sharing)
* any further steps to reproduce

**Comment by kaydeath** [comment] 2016-09-29 04:38
I tried multiple videos from Youtube. Various music videos, and lets plays by my preferred Youtubers. Nothing worked. I tried clicking the button in the top left corner and right-clicking the link and selecting the "Open in Mini Player" option. I just updated Firefox to the most recent version today around 5:00 p.m. I got everything from the Test Pilot, and when I tried to use the Mini Player, it didn't work. As mentioned above, the video will freeze, and stop responding completely. Operating System: Windows 10 Home 64-bit (10.0, Build 14393)

**Comment by Softvision-VladBacia** [comment] 2016-09-29 08:58
@kaydeath , we did a bit of investigation on this issue and tried to reproduce it. We installed all add-ons from Test Pilot before Firefox update, installed all add-ons from Test Pilot after Firefox update, installed all add-ons without Min-Vid from Test Pilot before Firefox update and after Firefox update we've installed Min-Vid add-on. Following scenarios we couldn't reproduce the issue. All supported videos from www.YouTube .com were played and the Min-Vid player was displayed.

Please, provide us a link to the video which didn't work for you. Did you use some custom config in Firefox? There were some particular steps in your scenario?

**Comment by kaydeath** [comment] 2016-09-29 17:01
Ok, so I uninstalled Firefox completely, reinstalled it, and now it works. I don't know what was wrong. Thank you for your assistance though. Here is the link to the video. https://www.youtube.com/watch?v=Vpqfll0GxZ4

**Comment by grebnetiew** [comment] 2016-10-14 17:34
I have the same problem. The first time I clicked the button on [this youtube video ](https://www.youtube.com/watch?v=VVaNq9uSJgY) (don't judge me :P) Firefox froze for half a minute and then nothing happened. Subsequent clicks just didn't do anything. Right-click-send-to-mini-player doesn't do anything.

OS Windows 10 x64
Firefox 49.0.1
Test Pilot: only MinVid
Add-ons: Chrome store foxified, Dom inspector, Fire gestures, Ghostery, Greasemonkey, Lastpass, Minvid, Nuke Anything Enhanced, Rikaichan, two dictionary addons for Rikaichan, Tabmix plus, Test pilot.

I have to do stuff now, so I don't really have time for disabling the addons one by one and restarting 99 times, but maybe later :)

**Comment by Softvision-VladBacia** [comment] 2016-11-21 14:37
@grebnetiew , I have created a new profile on Firefox latest release v50.0 and latest Nightly (Build ID: 20161104212021) and installed all the add-ons mentioned by you. For testing I have used latest Min-Vid v0.3.3-dev. I had no issues in playing the video in the mini player.

**Comment by meandavejustice** [comment] 2016-11-21 16:00
Sounds like this was fixed, possibly in #475, closing.

**Closed by meandavejustice** 2016-11-21 16:00 UTC
