### ISSUE TITLE
Min-Vid disappears if I open the Test pilot menu

### ISSUE THREAD

**Issue by seiferflo** [meandavejustice/min-vid#361] opened 2016-09-29 14:09 UTC
Hi.
Start a video from youtube, open the min-vid, wait for the video to start then click on the test pilot menu icon. The audio drops for half a second and the min-vid disappears. 
The video is still running in the background but no way to see or interact with the min-vid

Solutions:  closing the browser 
or Clicking on the min-vid icon on the youtube video but in that case it reloads a min-vid that will never start unless I reload the whole youtube page.

Thanks for your feedback.
Best Regards

**Comment by Softvision-VladBacia** [comment] 2016-09-29 14:13
@seiferflo , thank you very much for reporting this to us.

Unfortunately this issue is a dupe of #347 .

**Closed by Softvision-VladBacia** 2016-09-29 14:13 UTC

**Comment by seiferflo** [comment] 2016-09-29 14:20
@Softvision-VladBacia Oups, sorry !
