### ISSUE TITLE
Fast drag causes minvid window to lag behind the cursor

### ISSUE THREAD

**Issue by collectorgeneral** [meandavejustice/min-vid#989] opened 2017-08-16 02:17 UTC
Firefox 55.0.1 x64, Windows 7 x64.

Steps to reproduce:
Left click and hold the minvid window. Now rapidly move the mouse from one corner of the screen to another.

What happens?:
The minvid window, instead of staying with the cursor, falls behind the cursor at some point and hangs out at some spot. Further, releasing the mouse button and moving the cursor close to the minvid window just causes it to suddenly follow the cursor and keep moving below it. 

Expected behaviour:
Either the window should rapidly move around with the cursor, or just ignore the movement altogether.

**Comment by Softvision-VladBacia** [comment] 2017-08-16 08:23
@collectorgeneral Thank you for reporting this. This is a duplicate of #909

**Closed by Softvision-VladBacia** 2017-08-16 08:23 UTC

**Comment by collectorgeneral** [comment] 2017-08-16 12:47
@Softvision-VladBacia Thanks! Will keep an eye out for the issue.
