### ISSUE TITLE
Make player resizable

### ISSUE THREAD

**Issue by mohitkyadav** [meandavejustice/min-vid#1098] opened 2017-10-27 02:33 UTC
Please make the player resizable. Sometimes I watch some tutorials and have to code and watch side by side. It's impossible to see the code in current side.

**Comment by SoftVision-CiprianMuresan** [comment] 2017-10-27 11:31
Hi @mohitkyadav, thanks for the report. However it is a dupe of #69. If you navigate to about:addons->Extensions and double click the Min Vid add-on you can find 2 fields that can help you resize the player window.

![capture](https://user-images.githubusercontent.com/18304511/32102063-6aff50aa-bb23-11e7-8ddd-454e583f47da.PNG)

**Closed by SoftVision-CiprianMuresan** 2017-10-27 11:31 UTC

**Comment by mohitkyadav** [comment] 2017-10-27 11:41
@SoftVision-CiprianMuresan thanks but It would be more user friendly if we can resize the player with mouse, just like we do any other window.

**Comment by SoftVision-CiprianMuresan** [comment] 2017-10-27 11:45
I know, but that is currently tracked in #69. The fields in about:addons are a workaround for this until #69 is fixed.
