### ISSUE TITLE
Sound continues after min-vid is closed

### ISSUE THREAD

**Issue by kaganjd** [meandavejustice/min-vid#101] opened 2016-07-25 22:09 UTC
Video keeps playing even after I click the 'X'. It stops playing if I send another vid to min-vid.

**Comment by meandavejustice** [comment] 2016-07-25 22:20
dupe of #84

**Closed by meandavejustice** 2016-07-25 22:20 UTC
Labels: bug, duplicate

**Comment by meandavejustice** [comment] 2016-07-25 22:22
This is addressed in https://github.com/meandavejustice/min-vid/pull/93
