### ISSUE TITLE
min-vid is not working on firefox 55.0 (64-bit)

### ISSUE THREAD

**Issue by Abxol** [meandavejustice/min-vid#967] opened 2017-08-10 00:26 UTC
I can't play any video from youtube, I've tried on youtube's new version and the old one too, I uninstall the complement and install again and nothing gonna happend

**Comment by nemanjan00** [comment] 2017-08-10 11:34
56 also.

**Comment by Softvision-VladBacia** [comment] 2017-08-10 11:55
@Abxol , @nemanjan00 thank you for reporting this. 

Could you please provide more info regarding this issue:
- operating system
- how and from where are you installing Min-Vid

Min-Vid is not yet compatible with YouTube's new UI. The UI is experimental, for now.

**Comment by Abxol** [comment] 2017-08-10 12:50
Operative system: Windows 10 Pro X64
I installed min-vid from test pilot program

I've discovered something, min-vid works with some videos and it doesn't with other ones

https://www.youtube.com/watch?v=FAq4OIRDo68     NO WORK
https://www.youtube.com/watch?v=XFRfrPkfghY        IT WORKS

**Comment by nemanjan00** [comment] 2017-08-10 12:54
OS: Arch Linux

Installed from: 
https://testpilot.firefox.com/experiments/min-vid

Button for opening popup is not there.

**Comment by Softvision-VladBacia** [comment] 2017-08-10 15:42
@Abxol , some youtube videos are restricted from being embedded by the publisher, there isn't much we can do about this while following the terms of the api besides show an error message. (quoting @meandavejustice )

**Comment by nemanjan00** [comment] 2017-08-10 17:30
@Softvision-VladBacia, any ideas about my problem? 
Was anyone else able to reproduce it?

**Comment by Softvision-VladBacia** [comment] 2017-08-11 08:10
@nemanjan00 do you have the New YouTube UI or the old one? 

I have Ubuntu 14.04 and Min-Vid installed from Test Pilot and the player is working properly. There are no issues on my end.

**Comment by nemanjan00** [comment] 2017-08-11 10:48
Old UI. 
Which version of firefox do you use? 
I am on developer edition. (56.0b1 (64-bit))

**Comment by Softvision-VladBacia** [comment] 2017-08-11 11:40
- I have Nightly 57, here all is working properly.
- On the beta channel there is another story. Due to a sandboxing issue (that is fixed in Nightly) multiple components are not working properly. A workaround for this issue will be setting `security.sandbox.content.level` from `about:config` to 0 (from 3). A future browser update will fix this issue.

**Comment by nemanjan00** [comment] 2017-08-14 11:17
@Softvision-VladBacia, so, you are using Nightly?

**Comment by Softvision-VladBacia** [comment] 2017-08-16 08:04
@nemanjan00 , yes. I am using Nightly. In order to use the Min-Vid experiment (from Test Pilot) on Nightly 57 you must set the pref `extensions.legacy.enabled` to `true` from `about:config`.

**Comment by mystfox** [comment] 2017-08-16 11:38
It's not working for me with Firefox 57, even with that option set. Disabling and enabling it causes this to come up in the browser console, of which the second line looks very relevant?
```
1502883154026	addons.xpi	WARN	Add-on @min-vid is missing bootstrap method shutdown
1502883155284	addons.xpi	WARN	Error loading bootstrap.js for @min-vid: Module `resource://gre/modules/commonjs/sdk/addon/bootstrap.js` is not found at resource://gre/modules/commonjs/sdk/addon/bootstrap.js (resource://gre/modules/commonjs/toolkit/require.js:61) JS Stack trace: require@require.js:61:12 < @jar:file:///C:/Users/myst/AppData/Roaming/Mozilla/Firefox/Profiles/cs23jtkj.default/extensions/@bootstrap.js:10:23 < loadBootstrapScope@XPIProvider.jsm:4250:9 < callBootstrapMethod@XPIProvider.jsm:4317:9 < updateAddonDisabledState@XPIProvider.jsm:4536:13 < set userDisabled@XPIProvider.jsm:5524:9 < doCommand@extensions.js:1284:9 < set_userDisabled@extensions.xml:1126:13 < oncommand@about:addons:1:1
1502883155286	addons.xpi	WARN	Add-on @min-vid is missing bootstrap method startup```

**Comment by Softvision-VladBacia** [comment] 2017-08-16 12:20
@mystfox , the issue  is caused by [Bugzilla 1350646](https://bugzilla.mozilla.org/show_bug.cgi?id=1350646) .

**Comment by meandavejustice** [comment] 2017-08-16 22:39
Latest push fixes this issue. There was an issue with the build script we were using not working with our deployment environment.

**Closed by meandavejustice** 2017-08-16 22:39 UTC
