### ISSUE TITLE
Unable to load new video if video player is minimized

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#286] opened 2016-09-22 03:32 UTC
### Steps to reproduce:
1. Go to https://www.youtube.com/watch?v=F4POiFq3Dcc&t=41 and send the video to the mini player by hovering over the YouTube video.
2. Minimize the video. It should still play some ragtime-esque music in the background.
3. Hover over the YouTube video in the background and again send the video the mini player by hovering over the YouTube video. The music should still play.
4. Maximize the video player. It should still be playing music, but you'll see the "Loading video from youtube.com". It never seems to load, but you still can hear music.

![min-vid-mario-galaxy](https://cloud.githubusercontent.com/assets/557895/18734207/e6b899c4-8026-11e6-97ee-192a0c8886e4.gif)

**Comment by meandavejustice** [comment] 2016-09-27 16:04
@pdehaan I'm having trouble reproducing this today

**Comment by 6a68** [comment] 2016-09-27 21:05
I'm seeing a different set of symptoms here:

- go to the video
- load the video by clicking the overlay icon
- video starts playing
- minimize the player
- load the video again via overlay icon
- I see the loading screen shown forever, but the audio does stop from the previous track.

minimized player with loading screen looks like this on mac:

<img src="https://www.dropbox.com/s/772ilytvf38liaj/Screen%20Shot%202016-09-27%20at%202.03.37%20PM.png?dl=0&raw=true" width="400">

**Comment by Softvision-VladBacia** [comment] 2016-09-28 13:42
I have tried on Ubuntu 14.04 the steps from @6a68 [commen](https://github.com/meandavejustice/min-vid/issues/286#issuecomment-249998574) and this is how the player looks:
![minimized player with loading screen on linux](https://cloud.githubusercontent.com/assets/9248513/18915607/414aa292-859a-11e6-814e-7ac97d0f200f.png)

**Comment by meandavejustice** [comment] 2016-12-23 20:49
I'm no longer able to reproduce this. Assuming this was fixed in #475 and just was overlooked on the issue clean up

**Closed by meandavejustice** 2016-12-23 20:49 UTC
