### ISSUE TITLE
No support for twitch.tv videos

### ISSUE THREAD

**Issue by vmoutoussamy** [meandavejustice/min-vid#354] opened 2016-09-29 10:50 UTC
Hi,

I don't see the Min Vid icon when playing a stream on twitch.tv so I'm assuming that it's not supported. Supporting this plateform would be great!

Regards,

**Comment by meandavejustice** [comment] 2016-09-29 11:49
dupe of #6 closing

**Closed by meandavejustice** 2016-09-29 11:49 UTC
