### ISSUE TITLE
Can't move window

### ISSUE THREAD

**Issue by MindlessCirno** [meandavejustice/min-vid#1145] opened 2017-12-11 14:15 UTC
Popup can't be dragged at all on Firefox 59.0a1 (2017-12-11) (32-bit)

**Comment by Softvision-CristinaBadescu** [comment] 2017-12-11 14:40
Hello,

Thanks for reporting this. 
I've managed to reproduce it on latest Nightly build 59.0a1 (2017-12-11) using the latest Min Vid v0.4.6 from Test Pilot experiment page, on Windows 10 x64.

I've managed to find a regression-window. Here are the results:
Last good revision: b4d98531124336af6ebd253f9e9fd4aa5a53df30
First bad revision: a90317cd54ba39d47ded48c048bfd695e53c7bcd
Pushlog: https://goo.gl/TL7Czc

From the pushlog it seems that bug #[1228841](https://bugzilla.mozilla.org/show_bug.cgi?id=1228841) might have caused this.
@meandavejustice , can you please take a look at this issue? Also, do you think we should log this bug on Bugzilla?

**Comment by bodydisplaynone** [comment] 2017-12-12 09:00
I also can confirm this issue on the latest Nightly. MinVid is stuck on the top left corner and won't move at all.

![image](https://user-images.githubusercontent.com/22660372/33875687-4f3c138e-df23-11e7-9179-5b18834c753d.png)

**Comment by SoftVision-PaulOiegas** [comment] 2017-12-12 09:19
Yes, it's a regression caused by a change that occurred recently in Nightly. The development team was informed and we'll see what course of action will be taken in the next days.

In the meantime you can either use your current profile with Developer Edition, Beta or Firefox Release to bypass the issue. Those channels are not containing the latest changes from Nightly.

**Comment by imyxh** [comment] 2018-01-09 01:04
Temporary workaround: on many Linux distributions, including Ubuntu, you can move the window by pressing <kbd>Alt</kbd>+<kbd>F7</kbd> and the keyboard keys. Similarly, you can also resize it with <kbd>Alt</kbd>+<kbd>F8</kbd>. Maybe there's an equivalent on Windows and OSX.

**Comment by japodhidev** [comment] 2018-01-22 15:48
I managed to find a workaround to the inability to drag problem.

Press <kbd>Alt</kbd> + <kbd>TAB</kbd> and select the Min Vid window as the active window/bring it into focus.
Press <kbd>Alt</kbd> + <kbd>SPACE</kbd> to display a small dropdown menu.
Press <kbd>M</kbd> or manually select the <kbd>Move</kbd> option from the menu.
Use the arrow keys on your keyboard to move the window to your preferred position.

_Once the <kbd>Move</kbd> option is selected the window sticks to the mouse pointer. It moves together with the mouse pointer movement. Use the <kbd>ESC</kbd> key to return to normal mouse pointer functionality._

**Comment by 6a68** [comment] 2018-01-24 03:16
The upstream bug removed support for [conditional `catch` clauses](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#Conditional_catch_clauses), like `catch (e if <condition>)`.

This non-standard usage occurs in a single spot inside ostypes. Should be a one-liner fix

**Comment by SoftVision-CarmenFat** [comment] 2018-01-25 12:53
Tested this using latest Nightly 60.0a1 (2018-01-24) and latest Developer Edition 59.0b3 with the latest Min Vid version 0.4.7 - shield study (custom built on 01/25/2018) and here are the results:
- on Windows 10 x64 and macOS 10.12, the issue is fixed: the mini player is no longer stuck and can be dragged across the screen display.
- on Ubuntu 10.14 x64 and 10.16 x64, the issue is not fixed: the mini player is still stuck and cannot be moved by the user.

**Comment by 6a68** [comment] 2018-01-25 16:48
Hi @SoftVision-CarmenFat, as I mentioned in #1200, I suspect the remaining linux issue has a different root cause, and the shield study focuses on windows, which is now fixed. Could you reopen a linux-specific bug?

**Closed by 6a68** 2018-01-25 16:48 UTC
