### ISSUE TITLE
Frame rate could be better

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#330] opened 2016-09-28 13:00 UTC
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.2.6-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.2.6-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to the mini player and choose to play it.
4. Observe the video playback smoothness for a few seconds (20-30 seconds).

[Expected result]:
- The video is fluently played no matter how long you watch it.

[Actual result]:
- Mild, yet constant stuttering can be observed throughout the video.

[Notes]:
- The same behaviour can be observed on the latest Nightly with e10s enabled.
- I've also tested with older Min-Vid builds and with Nightly builds before the SDK changes and it seems that the issue was always there, but you need to watch carefully.
- We don't consider this a blocker, but it could affect the user's satisfaction when watching videos.

**Comment by 6a68** [comment] 2016-09-28 14:21
@SoftVision-CiprianMuresan I've seen this on high frame rate ("HFR") videos. The audio track stays synced perfectly, but some frames are dropped.

Since min-vid is a preview or background player, I agree that this isn't a blocker.

I'm not sure if this is due to the iframe being downsized relative to the original, limitations that youtube/vimeo deliberately put into their embed players, or something else.

**Comment by 6a68** [comment] 2016-09-28 18:17
It turns out that panels aren't hardware accelerated. That's why the frame rate is laggy.

I'll work on a fix this week.

**Comment by meandavejustice** [comment] 2016-11-16 19:46
Should be fixed in #475

**Closed by meandavejustice** 2016-11-16 19:46 UTC

**Comment by Softvision-VladBacia** [comment] 2016-11-21 13:06
This issue is no longer reproducible with the latest Min-Vid build v0.3.3-dev using latest Firefox release 50.0 and latest Nightly build (Build ID: 20161120030205). We tested also with hw acceleration ON and OFF.
