### ISSUE TITLE
The screen can not be moved along the window.

### ISSUE THREAD

**Issue by suelinton** [meandavejustice/min-vid#1193] opened 2018-01-22 18:22 UTC
After update of the firefox to the version 59.0b2 (64-bit) the screen of the min-vid can not be moved along the window and never it's in front of others screens.

**Comment by SoftVision-CarmenFat** [comment] 2018-01-23 08:00
Thanks for reporting this issues, however, this is a dupe of #[1145 ](https://github.com/meandavejustice/min-vid/issues/1145)and #[1149](https://github.com/meandavejustice/min-vid/issues/1149). The development team was informed and we'll see what course of action will be taken.

**Closed by SoftVision-CarmenFat** 2018-01-23 08:00 UTC
