### ISSUE TITLE
[YouTube] Releases the window when start drag 

### ISSUE THREAD

**Issue by QAtestbegining** [meandavejustice/min-vid#1191] opened 2018-01-21 11:40 UTC
[Affected versions]:

- Firefox Quantum 57.0.4

[Affected Platforms]:

- All Windows

[Prerequisites]:

- Latest Min-Vid add-on(0.4.7)

[Steps to reproduce]:

1. Open the browser with the profile from prerequisites and navigate to https://youtube.com.
2. Play some video via Min Vid
3. Start drag the Min Vid window 
4.Observe what happens next.

[Expected result]:

- Drag the window every where on the screen faster as you can

[Actual result]:

- When start drag the window from the upper side(only) fast the cursors releases the window

[Notes]:

- I did not try to reproduce the issue on Mac and Linux
- Attached a screen recording of the issue:
![2018-01-21_13-18-17](https://user-images.githubusercontent.com/35638229/35193757-1f60b0fa-feb0-11e7-8dc6-0377969af315.gif)

**Comment by Softvision-CristinaBadescu** [comment] 2018-01-22 08:21
Thanks for reporting this. However, this is a dupe of #909.

**Closed by Softvision-CristinaBadescu** 2018-01-22 08:21 UTC
